hashicorp/consul-terraform-sync

cli.go
Recent change returns an error for no config files, which revealed that version flag was processed after loading configs. Swapped the order to exit earlier
=> Return version before processing config files

config/terraform.go, config/terraform_test.go, e2e/config.go, e2e/e2e_test.go
We want to support local backend in addition to Consul backend. This will support users who need to persist their state file when they spin up/down their Consul agent.
Include e2e tests to document how configuring local backend’s `path` and `workspace_dir` plays out for two tasks. Note: configuring `path` is not meaningful for Sync since `path` is used for the default workspace. Sync creates a custom workspace for each task and therefore does not work in the default workspace. This configuration information will be documented separately. See https://github.com/hashicorp/terraform/blob/master/backend/local/backend.go#L445 for more details on `path`
Resolves: https://github.com/hashicorp/consul-terraform-sync/issues/92
=> Add support for local Terraform backend

driver/terraform.go
I think the worker retry https://github.com/hashicorp/consul-terraform-sync/pull/72 was somehow missed in the refactor efforts https://github.com/hashicorp/consul-terraform-sync/pull/81. `defaultRetry` is 2 and was used in #72 and no longer referenced anywhere after #81
=> set default retry count

cli.go, config/config.go, config/config_test.go, config/testdata/long.hcl, config/testdata/long.json, config/testdata/override/a.hcl, config/testdata/override/b.hcl, config/testdata/simple.hcl, config/testdata/simple/b.hcl
This aligns the daemon modes to be controlled only by CLI flags, similar to the support for Once.
Having inspect mode as a config option requires multiple steps for a debugging option to change modes that would be better without -- write config file, save, run the program, then later open config, delete option, save, run again
Note, at this point `inspect` flag is not available and is not implemented yet, just shifts existing code around
=> Remove inspect mode from config file option

cli.go, client/terraform_cli.go, config/task.go, controller/controller.go, controller/controller_test.go, controller/readonly.go, controller/readonly_test.go, controller/readwrite.go, controller/readwrite_test.go, driver/driver.go, driver/task.go, driver/task_test.go, driver/terraform.go, mocks/driver/driver.go, templates/tftmpl/root.go
Implements support for inspect mode. This PR adds 2 CLI flag options to run inspect mode
1. `-inspect` which runs all tasks
1. `-inspect-task` to run selected task by name
* Moved core content of initializing the controller to a new `baseController` to use struct-embedding for composition.
* Moved test along with slight refactor to condense testing methods with similar test setup
* Add `InspectTask` which corresponds to Terraform plan on the driver level.
* Refactor worker retry to accept a function instead of implementing 1:1 worker functions to client
* Small fix to isolate Terraform CLI client from template concepts (".tmpl" file suffix)
```
$ consul-terraform-sync -h
Usage of consul-terraform-sync:
...
-inspect false
Run Sync in Inspect mode to print the proposed state changes for all …
```
=> Inspect mode

cli.go, controller/controller.go, controller/controller_test.go, controller/readwrite_test.go, driver/driver.go, driver/task.go, driver/task_test.go, driver/terraform.go, driver/terraform_download.go, driver/terraform_test.go, driver/worker.go, driver/worker_test.go, mocks/driver/driver.go
PR proposes to condense down the layers of abstraction. It started growing to where all information were being passed down to each level controller > driver > worker > task.
* Moves worker code to separate file
* Refactors worker to reduce the context required for a worker - no longer needs info on client, init history, task.
* Moves driver install outside of controller workflow so it is only checked and installed once and earlier, instead of installing/verifying install for each task since there can only be one driver version used across all tasks
* Doubles down on the recent design choice for a driver instance per task.
* TF driver now manages the TF client directly and initializes it within the constructor. This no longer requires the driver to store extra info that only pertains to …
=> Refactor worker and driver

config/terraform.go, config/terraform_test.go, controller/controller.go, templates/tftmpl/root_test.go
Enables usage of other Terraform backends for state store that support [workspaces](https://www.terraform.io/docs/state/workspaces.html) and state locking.
Tests capture testing the integration of passing through backend configuration to the generated root main.tf file. Validity of the backend configuration options are done at task execution time. Each backend were not tested directly to avoid testing Terraform functionality, but I did test the [postgres](https://www.terraform.io/docs/backends/types/pg.html) and came across a bug that prevents CTS from allowing it to be used with Terraform 0.13.
This PR does not allow usage of the pg backend since CTS is currently bounded to Terraform 0.13. However it will be accessible soon as we're looking to expand support for Terraform 0.14 (#127).
=> Expand usage of Terraform backends for state store

controller/controller.go, controller/readwrite.go, controller/readwrite_test.go, driver/task.go, driver/task_test.go, event/event.go, event/event_test.go, go.mod
First part in a series of changes to support a status api. This captures data in
an `Event` struct each time CTS goes through the process needed for updating
network infrastructure for a task. Future changes will store the event data and
return various aggregations of the data at the api endpoint
Changes
- Create `event` package & structure
- Consume event in controller checkApply()
- Update `unit` with provider, service, and source in order to configure `event`
- Update `Task` with ProviderNames() & ServicesNames to help configure `event`
=> Capture data on process of updating network infrastructure in `Event`

config/config_test.go, config/driver_test.go, config/terraform.go, config/terraform_test.go, controller/controller.go, driver/terraform_download.go, driver/terraform_download_test.go, examples/sync-tasks/my-task/main.tf, templates/tftmpl/root.go, templates/tftmpl/root_test.go, templates/tftmpl/testdata/main.tf, version/terraform.go, version/terraform_test.go
I did a first pass at reading through the [Terraform 0.14 changelog](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md) and did preliminary tests with changing versions with existing tasks. Nothing strikes me as breaking changes with regards to CTS usage of Terraform.
* Adds configuration option to select Terraform version
* Configured version mismatch with existing TF in path will skip installation and use the existing one. If users choose to update TF versions, they will need to resolve this manually by removing the existing version first.
```hcl
driver "terraform" {
version = "0.13.5"
}
```
* Allows CTS to run Terraform 0.14 in automation (when released).
* Prereleases are incompatible with CTS (alpha, beta, etc), e.g. the current 0.14-beta2 cannot be ran in automation …
=> Configurable Terraform version and v0.14 support

controller/controller.go, go.mod, go.sum, templates/tftmpl/template_funcs.go
The changes fixes the case where CTS would hang indefinitely when
running on a machine with DNS issues that cause timeouts while
connecting to Consul. Added a log line to provide users context
about attempting Consul connection for easier debugging connection
issues instead of hanging silently.
Context: https://github.com/hashicorp/hcat/issues/23
=> Pull in hcat bug fix on Consul connect timeouts

cli.go, controller/controller_test.go, controller/readwrite.go, controller/readwrite_test.go, event/event.go, event/event_test.go, event/store.go, event/store_test.go, main.go
Second part in a series of changes to support a status api. This stores event
data in memory when running in daemon mode. Future changes will return
aggregations of the stored events at the api endpoint.
Changes
- Create `store` struct with ability to add and read
- Update readwrite controller (+ tests) with a `store` field
- Store events that are crated in checkApply()
=> Store event data

config/config.go, config/config_test.go, config/provider.go, config/provider_test.go, config/testdata/long.hcl, config/testdata/long.json, controller/controller.go, controller/controller_test.go, controller/readwrite_test.go, e2e/config.go, examples/example-config.hcl
This is to further distinguish the syntax and features supported by Terraform provider blocks and CTS terraform_provider blocks, like supporting dynamic configuration.
related #53
=> Deprecate provider block for terraform_provider

api/api.go, api/api_test.go, api/task_status.go, api/task_status_test.go, cli.go, controller/readwrite_test.go, event/event.go, event/event_test.go, event/store.go, event/store_test.go, main.go
Third part in a series of changes to support status api. This adds basic use
case for task status endpoints `/status/tasks` and `/status/tasks/{task_name}`.
Future work listed below.
Changes
- Change event store.Read() to support read-all when empty task name is passed
- Change event store.Read() to return map[string][]Event instead of []Event
- Add api package that serves the api and contains handlers
- Removed store from main.go and serve api in cli.go rather than main.go
Since this PR was growing a bit large, subsequent PRs will have:
- configuring the api port
- e2e test
- filter by status e.g. ?status=critical
- include events in payload e.g. ?include=events
- overall status endpoint
Examples:
`/v1/status/tasks`:
```
{
"test_a": {
"task_name": "test_a",
"status": "healthy", …
```
=> Add basic task status endpoint

Makefile, api/api.go, api/api_test.go, api/overall_status.go, api/overall_status_test.go
Part of a series of changes to support status api. Adds an endpoint that gives the overall status of all the tasks that cts executes. Overall status is determined by task status information for all tasks
Example:
`GET /v1/status`
`
{"status":"healthy"}
`
=> Add overall status endpoint

Makefile, cli.go, config/config.go, config/config_test.go, config/convert.go, config/testdata/long.hcl, config/testdata/long.json, config/testdata/override/a.hcl, config/testdata/override/b.hcl, config/testdata/simple/a.hcl, controller/controller_test.go, e2e/config.go, examples/example-config.hcl
- Add new `port` config at top-level
- Update api to consume new port config
- Update e2e test config to dynamically choose next free port
- Fix a controller test to dynamically choose next free port
=> Support api port configuration

api/api.go, api/api_test.go, controller/readwrite.go, e2e/api_test.go, e2e/config.go, handler/fake.go, handler/fake_test.go
Adds an e2e test for task status endpoints. Uses a fake-handler which passes
once-mode but subsequently produce errors to create failed events. Runs cts in
development in order to use fake-handler.
Changes
- Update fake-handler to return nil error initially and then error afterwards
- Refactor out finding next free port into a method
- Move events so that they’re only added once results templates are rendered
(discovered by e2e test)
- e2e test for basic task status and overall status  endpoint
=> Task status e2e test

api/api_test.go, api/task_status.go, api/task_status_test.go, e2e/api_test.go
Update task status endpoint to support a `?include=events` parameter. When this
parameter is included, the task status payload will include an `Event` field
containing an array of the events that inform the task status.
Example:
`GET /v1/status/tasks/task_a?include=events`
```
{
"task_a": {
"task_name": "task_a",
"status": "healthy",
"providers": [
"local"
],
"services": [
"api",
],
"events_url": "/v1/status/tasks/task_a?include=events",
"events": [
{
"id": "44137ba2-8fc9-6cbe-0e0e-e9305ee4f7f9",
"success": true,
"start_time": "2020-11-24T12:06:51.858292-05:00",
"end_time": "2020-11-24T12:06:52.770165-05:00",
"task_name": "task_a",
"error": null,
"config": {
"providers": [
"local"
],
"services": [
"api",
],
"source": "../modules/e2e_basic_task"
}
}
]
}
}
```
=> Support `?include=events` parameter for task status

api/task_status.go, api/task_status_test.go, e2e/api_test.go
Update task status endpoint to support a `?status=<health_status>` parameter
where `<health_status>` values are: healthy, degraded, critical, undetermined. When the
parameter is included, the task statuses will be filtered to only include those
which have a status that matches the status query parameter value.
Example:
`GET /v1/status/tasks?status=critical`
```
{
"task_b": {
"task_name": "task_b",
"status": "critical",
"providers": [
"local"
],
"services": [
"api",
],
"events_url": "/v1/status/tasks/task_b?include=events"
},
}
```
=> Support `?status=<health_status>` parameter for task status

controller/readwrite.go, controller/readwrite_test.go
Addresses feedback in https://github.com/hashicorp/consul-terraform-sync/pull/144
Additional improvements:
- Log error on store.Add()
- Rename errors that will be stored in events so that they can be more easily
identified
=> Store event when fetching template dependencies errors

cli.go, controller/controller.go, controller/readonly.go, controller/readonly_test.go, controller/readwrite.go, controller/readwrite_test.go, mocks/templates/watcher.go, templates/hcat.go
`hcat.Watcher.Stop()` closes out client idle connections. It was not being called for 3 shutdown scenarios
* Errors
* Once mode
* Inspect mode
Changes now ensure the controller calls stop on its watcher. Also adds conditional logging on the hcat dependency size. This PR doesn't fix #146 where CTS quickly reaches the connection limit for the Consul agent, but is related to help debug.
Resolves #149
=> Fix leaky idle connections on shutdown

client/client.go, client/printer.go, client/terraform_cli.go, config/provider.go, config/provider_test.go, controller/controller.go, controller/controller_test.go, driver/task.go, driver/task_test.go, driver/terraform.go, driver/terraform_provider.go, driver/terraform_test.go, mocks/client/client.go, templates/hcltmpl/block.go, templates/hcltmpl/dynamic_test.go
Adds support for `terraform_provider` blocks to configure provider environment variables using the meta block `task_env`. Dynamic config source is supported within the `task_env` block.
```hcl
terraform_provider "foo" {
address = "foo.example.com"
task_env {
"FOO_TOKEN" = "{{ env \"CTS_FOO_TOKEN\" }}"
}
}
```
This is useful to keep sensitive provider arguments out of the generated `terraform.tfvars` for each task. The environment variables are passed to Terraform workspaces that use that provider. The envvars are not accessible to other tasks or set to the global env scope.
The `task_env` is also useful to decouple the expected environment name for Terraform providers. A few use cases here:
* CTS configuring multiple instances of a provider for different tasks. Without the `task_env` …
=> Add task_env to provider blocks

CHANGELOG.md, config/config.go
- Anticipate that CTS will be run on the same node as Consul
- Port 8501 is reserved by Consul. Other Consul reserved ports:
https://www.consul.io/docs/install/ports#ports-table
- Consul team recommends using port in 8500s for http api and has no
reservations for 8558 for current and future work as of now
- 8558 is not a known/taken/reserved port with IANA
=> Change default port that API is served

api/api.go, api/api_test.go, api/overall_status.go, api/overall_status_test.go, api/task_status.go, api/task_status_test.go, e2e/api_test.go
- 'healthy' => 'successful'
- 'degraded' => 'errored'
- 'undetermined' => 'unknown'
Subsequent PRs will update with the new 'calculation' of these statuses
=> Rename health status language

api/overall_status_test.go, api/task_status.go, api/task_status_test.go, e2e/api_test.go, event/store.go
The last task execution determines if the network infra is synchronized with Consul.
**Note**: the logic for Overall status is not updated within this PR and do not reflect the end goal of overall. The tests are updated just to pass.
=> Change events status logic to focus on latest event

api/api_test.go, api/overall_status.go, api/overall_status_test.go, e2e/api_test.go
Rather than returning a status value to represent the overall status across all
tasks, return a field 'task_summary' that shows how many tasks have each health
status value.
Example: `curl localhost:8558/status`
```
{
"task_summary": {
"successful":8,
"errored":2,
"critical":1
}
}
```
Note: currently didn't add "unknown" status in the summary since that would require retrieving tasks that we don't have event information for yet. Doable but omitted in this PR. Open to feedback on adding it before release!
=> Update Overall Status to return status count summary

client/terraform_cli.go, config/terraform.go, config/terraform_test.go
Updates code comments to include more context on end result of the KV path for stored state files
=> Fix Consul KV path appending terraform suffix 2x

config/config_test.go, config/testdata/long.hcl, config/testdata/long.json, config/transport.go, go.sum
`http.MaxIdleConnsPerHost` was default to a very low value that caused TCP connections to not be reused across hcat dependency monitoring. Only ~1 connections were being reused from the initial set of hcat requests to Consul, and the remaining dependencies required establishing a new connection.
Changes:
* `DefaultMaxIdleConnsPerHost`: CTS default changed from 1 to 100 (the [transport default is 2](https://golang.org/pkg/net/http/#Transport) and [setting -1 disables keep alives altogether](https://golang.org/src/net/http/transport.go?s=3396:10951#L878)). This increases the # of reusable TCP connections for service monitoring. From 1:2 connections per service now to 1:1.
* `DefaultMaxIdleConns` default changed from 100 to 0, which disables the the limit. The previous limit not only caps …
=> Update default transport configurations

config/config_test.go, config/service.go, config/service_test.go, controller/controller.go, templates/tftmpl/integration_test.go, templates/tftmpl/root.go, templates/tftmpl/template_funcs.go, templates/tftmpl/template_funcs_test.go, templates/tftmpl/testdata/only_api_service.tfvars, templates/tftmpl/testdata/only_web_service.tfvars, templates/tftmpl/testdata/terraform.tfvars, templates/tftmpl/testdata/variables.tf, templates/tftmpl/tfvars.go, templates/tftmpl/variables.go
Adds a new option `cts_user_defined_meta` to the `service` configuration block for Consul Terraform Sync. This attribute is useful to insert metadata for a service to be used for network infrastructure automation and consumed by a Terraform module.
A driving use case for user-defined metadata within CTS is automating load balancers and associating a service with a virtual IP address. The current method is to insert the VIP into Consul service metadata during registration. However, it might not be desirable to insert NIA scoped metadata into Consul, where it may not be useful by applications aside from CTS. It would also require shared context of service to VIP mappings between a network administrator and the application developer. `cts_user_defined_meta` can now be used to keep the scope …
=> User defined metadata for services

config/config.go, config/config_test.go, config/task_test.go, handler/panos.go, handler/panos_test.go, templates/tftmpl/root.go, templates/tftmpl/root_test.go
Adds logic to support setting an 'auto-commit' boolean setting on providers that will control the out-of-band automatic commit on task run for providers than need it (eg. Panos).
Note there is no documentation. Seems like any relevant docs would live elsewhere.
=> add auto-commit setting support to providers

templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, templates/tftmpl/root.go, templates/tftmpl/testdata/main.tf, templates/tftmpl/testdata/variables.tf
When converting user-defined provider configuration into provider definition
blocks with variables, object-type attributes were formatted like
`obj = var.provider_name.obj`. This led to "Error: Unsupported argument".
This PR formats object-type attributes into a block like:
```
obj {
attr = var.provider_name.obj.attr
...
}
```
Fixes https://github.com/hashicorp/consul-terraform-sync/issues/171
=> Add support for provider configuration containing object-type attributes

go.mod, go.sum, templates/tftmpl/template_funcs_test.go, templates/tftmpl/testdata/only_api_service.tfvars, templates/tftmpl/testdata/only_web_service.tfvars, templates/tftmpl/testdata/terraform.tfvars, templates/tftmpl/testdata/variables.tf, templates/tftmpl/tfvars.go, templates/tftmpl/variables.go
Takes the newly supported hcat consul health service Kind value and
propagates it through to the module input fields.
Updated to use latest hashicat.
Add it to the services variable fields.
Rendered into templates via mapstructure rendering of data structs.
Tests and testdata updated.
Closes #168
=> include service kind in module input

go.mod, go.sum, templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, templates/tftmpl/root.go, templates/tftmpl/root_test.go, templates/tftmpl/template_funcs.go, templates/tftmpl/testdata/terraform.tfvars.tmpl, templates/tftmpl/tfvars.go
Service config blocks with namespaces defined can now query services based on namespace when deployed with Consul enterprise.
```hcl
service {
name = "app"
namespace = "app-team"
}
```
Configuring the service namespace without Consul enterprise will result in an exiting error:
```
2021/01/25 18:14:43.253097 [ERR] (cli) error running controller in Once mode: health.service(app?ns=app-team&filter="Checks.Status == passing"): Unexpected response code: 400 (Bad request: Invalid query parameter: "ns" - Namespaces are a Consul Enterprise feature)
```
Pulls in changes from  https://github.com/hashicorp/hcat/pull/35
Marking this with a bug label since the namespace option was available before it was fully supported.
=> Support querying service by namespace

Makefile, version/version.go
Small proposal to include `dirty` in the version output when the working tree has local modifications from HEAD. This is intended primarily for local development use.
```
$ consul-terraform-sync -version
consul-terraform-sync 0.1.0-beta (e3aa8cc dirty)
Compatible with Terraform >= 0.13.0, < 0.15
```
=> Add dirty to version output

driver/terraform.go, handler/fake.go, handler/fake_test.go, handler/handler.go, handler/handler_test.go, handler/panos.go, handler/panos_test.go
Handler's Do() methods need to be cancellable via context and having the context helps. This makes sure the context is passed along.
Split this out from panos-retry work.
=> propagate context through handlers

driver/terraform.go, driver/terraform_download.go, templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, templates/tftmpl/root.go, templates/tftmpl/testdata/variables.tf, templates/tftmpl/variables.go, templates/tftmpl/variables_test.go
Sensitive argument won't prevent provider args from being stored in the state files, but will omit them from Terraform output and logs.
Conditionally adds the `sensitive = true` to the generated `variables.tf` when the discovered/installed Terraform version is 0.14+
Resolves #85
=> Set provider intermediate variable as sensitive

examples/sync-tasks/my-task/terraform.tfvars, examples/sync-tasks/my-task/variables.module.tf, templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, templates/tftmpl/module_variables.go, templates/tftmpl/root.go, templates/tftmpl/testdata/only_api_service.tfvars, templates/tftmpl/testdata/only_web_service.tfvars, templates/tftmpl/testdata/providers.tfvars, templates/tftmpl/testdata/terraform.tfvars, templates/tftmpl/testdata/terraform.tfvars.tmpl, templates/tftmpl/testdata/variables.module.tf, templates/tftmpl/tfvars.go, templates/tftmpl/variables.go
Separating the provider vars allows the `terraform.tfvars` file to be more easily shareable now that potentially sensitive values are not included. This also removes provider info from being unnecessarily included in the `.tfvars.tmpl` template file.
Resolves #172
=> Separate provider vars from services var

config/provider.go, config/provider_test.go
HCL config unmarshals `task_env` to interface and type casting nested interfaces requires converting each item and not the collection -- `map[string]interface{}` and so the type validation expecting `map[string]string` would always fail and CTS would error and exit on configuration.
Related #157
Repro steps
1. Config file with `task_env` block for any provider
```hcl
terraform_provider "local" {
task_env {
"my_env" = "foo"
}
}
task {
name        = "test"
source      = "<any module>"
services = ["api", "web"]
}
```
2. Run CTS
```shell
$ consul-terraform-sync -config-file task_env.hcl -inspect
2021/02/04 18:14:47 [ERR] (cli) error validating configuration: unexpected task_env block format
```
=> Fix task_env type validation

controller/controller.go, controller/controller_test.go, controller/readwrite.go, driver/driver.go, driver/task.go, driver/terraform.go, mocks/driver/driver.go
Discovered a bug in earlier refactor https://github.com/hashicorp/consul-terraform-sync/pull/185.
If a task is configured as disabled from the start, a template will not be
generated and template == nil. readwrite.setTemplateBufferPeriods() calls
driver.TemplateID() which throws a nil pointer panic.
Refactor setTemplateBufferPeriods():
- Add controller.getTemplateBufferPeriods() and then set buffer info on driver.Task
- Add driver.SetBufferPeriods() which sets buffer info from driver.Task on watcher
- Update readwrite.Run() to call driver.SetBufferPeriods()
- Remove the need for driver.TemplateID()
=> Refactor buffer_period to driver-level

controller/controller.go, controller/controller_test.go, driver/task.go, driver/terraform.go, driver/terraform_test.go, e2e/config.go, e2e/e2e_test.go
- Previously added `enabled` field to task configuration
- Update driver methods to not make changes if task is disabled
- e2e test for configuring a disabled task
=> Consume `enabled` field in task driver

api/api.go, api/api_test.go, api/client_test.go, cli.go, controller/controller.go, controller/controller_test.go, controller/readonly.go, controller/readwrite.go, controller/readwrite_test.go, driver/terraform.go, driver/terraform_test.go
In order to support an update task API for the disable/enable cli feature, APIs
will need to call the drivers for the associated task.
Changes
- Update controller.Init() to also return a map of drivers
- Update API with a `drivers` fields
- Refactor cli to serve API after controller.Init() is called in order to
consume drivers
- Update driver to be concurrent with locks (separate commit)
(I have a subsequent PR that will consume the new drivers field in the API. The changes got sort of big so wanted to make separate PRs)
=> Share controller drivers with API

api/api.go, api/api_test.go, api/task.go, api/task_status.go, api/task_status_test.go, api/task_test.go, driver/driver.go, driver/task.go, driver/terraform.go, mocks/driver/driver.go
Add support for `PATCH /v1/tasks/<task_name> -data '{"enabled:"true}'`. This will
be used for the upcoming disable task CLI. Additional functionality will be
added in subsequent PRs for enable task CLI.
Changes (each correspond with a commit. See individual commit messages for
more details):
- Refactor api's getTaskName() to be shared across handlers
- Add driver.UpdateTask() to allow patch updating a task
- Add Update Task API
Note: ^ I tried to split out changes into commits. Not perfect. There's a couple lines
(particularly imports) that aren't in the right commit.
=> Add Update Task API with initial support to disable/enable a task

api/client_test.go, e2e/api_test.go, e2e/e2e_test.go, testutils/utils.go, testutils/utils_test.go
Changes:
- Refactor out makeTempDir to testutils
It was copied in two packages and we have at least one other test-helper-type method that would benefit from consolidating in a testing package
=> Make a testutils package to hold helper functions shared across packages

cli.go, command/commands.go, command/meta.go, command/task_disable.go, go.mod
`consul-terraform-sync task disable <task_name>`
Changes (each correspond with a commit. See individual commit messages for
more details):
- Some initial minimal CLI command support. Taken from Nomad and Terraform
- Support disable CLI (fixes some typos in previous change too)
Note: planning to write an E2E test once I also update Status API with enabled/disabled. In the test, then I will be able to run the disable CLI and use the status API to confirm changes in disabled/enabled.
=> Support disable CLI

api/api_test.go, api/client.go, api/client_test.go, api/task.go, api/task_test.go, command/task_disable.go
Support `?run=now` and `?run=inspect` in the Update Task API and client. The
enable CLI will use these to output a plan for the operator (?run=inspect) and
on approval execute the changes (?run=now).
Changes (each correspond with a commit. See individual commit messages for
more details):
- Update the API to parse for run param and call driver.UpdateTask accordingly
- Update the API client to pass in the run param and return plan
- Reorganize imports (from feedback https://github.com/hashicorp/consul-terraform-sync/pull/191#pullrequestreview-592717549)
=> Modify Update Task API & client with run query parameter

command/commands.go, command/meta.go, command/task_disable.go, config/config.go
Add `-port` as a default flag option for CLI commands. The default port remains as `8558`.
```
$ consul-terraform-sync task disable -port 2000 my_task
==> Waiting to disable 'my_task'...
==> Error: unable to disable 'my_task'
Patch "http://localhost:2000/v1/tasks/my_task": dial tcp 127.0.0.1:2000:
connect: connection refused
```
Changes overview
* Dynamically add flag options to Help output
```
$ consul-terraform-sync task disable -h
Usage: consul-terraform-sync task disable [options] <task name>
Task Disable is used to disable existing tasks. Once disabled, a task will no
longer run and make changes to your network infrastructure resources.
Options:
port 8558
The port to use for the Consul Terraform Sync API server
```
* Added additional help msg when flags and arguments are set out of …
=> command: add port flag option

cli.go
**Breaking change:** The output of the version flag was going to `stderr`. This changes the output to `stdout` to align with how other hashicorp tools are set.
```shell
$ consul-terraform-sync -version 1> stdout.txt
$ cat stdout.txt 
consul-terraform-sync 0.1.0-techpreview2 (7fbd5e1)
Compatible with Terraform >= 0.13.0, < 0.15
```
=> Change version output to stdout

api/api.go, api/client.go, api/error.go, api/task.go, api/task_status.go
**Breaking change**: This will give room for future details to be added to the API error responses.
Prior to change
```
{
"error": "unsupported status parameter value. only supporting status values successful, errored, critical, and unknown but got xxx"
}
```
After change
```
{
"error": {
"message": "unsupported status parameter value. only supporting status values successful, errored, critical, and unknown but got XXX"
}
}
```
=> Change API error from string to object

api/api.go, api/api_test.go, api/client_test.go, api/task_status.go, api/task_status_test.go, controller/readwrite.go, controller/readwrite_test.go, e2e/api_test.go, e2e/config.go
Example of updated return payload:
```
"task_a": {
"task_name": "task_a",
"status": "successful",
"enabled": false, // new field
...
}
```
Commits:
- Add driver to taskStatusHandler and use driver to add `enabled` information
to task status payload
- Support 'unknown' status for tasks that are disabled from the start (since
these tasks have never run, there is no event data  collected on them)
- Fix issue in controller where events were being stored even though tasks were
disabled
=> Update Task Status API to support enabled/disabled tasks

api/api.go, api/api_test.go, api/client_test.go, api/overall_status.go, api/overall_status_test.go, api/task_status_test.go, e2e/api_test.go
**Breaking change:** Reorganize the returned status payload to allow for
different breakdowns of task summary information
Example of new payload:
```
{
"task_summary": {
"status": { // move status info into this status sub-struct
"successful": 2,
"errored": 1,
"critical": 0,
"unknown": 0 // new field for disabled tasks with no event data
},
"enabled": { // add new enabled information
"true": 2,
"false": 1
}
}
}
```
Commits:
- Add driver to overallStatusHandler and use driver to add enabled information
to overall status payload. Refactor task summary to have status and enabled
sub-structures
- Refactor some testing methods
- Support 'unknown' status for tasks that are disabled from the start (since
these tasks have never run, there is no event data collected on them)
=> Update Overall Status API to support enabled/disabled tasks

e2e/api_test.go, e2e/config.go, e2e/e2e_test.go
Commits:
- Reuse TestE2EDisabledTask for Update Task API e2e test due to overlaps in
checks. Expand on disabled task to enable then disable and do checks
- Refactor functions that run CTS
=> Add e2e tests for Update Task API

driver/terraform.go
All other API responses are snake case. Instead of creating a dedicated API object that is 1:1 to the internal object, will just added JSON struct tags as a means to have the Update Task API to be consistent with snake case.
```
$ curl localhost:8558/v1/tasks/a -X PATCH -d '{"enabled":true}' | jq .
```
```diff
{
-  "ChangesPresent": false,
-  "Plan": ""
+  "changes_present": false,
+  "plan": ""
}
```
=> Task update API to be consistent JSON payload with snake_case

e2e/command_test.go, e2e/config.go, e2e/e2e_test.go
Changes
- Add test cases for cross subcommand errors that are defined in the meta object
- Test enable and disable task CLIs
- Mild refactor oneTaskConfig so that a port can be passed in
=> Add e2e tests for Disable and Enable Task CLIs

config/consul.go, config/terraform.go, config/tls.go, controller/controller.go, controller/controller_test.go, driver/task.go, driver/terraform.go
The default Terraform backend when ran by CTS is the Consul KV. Users would configure the Consul block in CTS configuration and assume the same configuration would be used for the Terraform Consul backend. However there were two edge cases not handled for configuring the default Consul backend.
1. Configuration values in Consul block for CTS configuration file were not passed to the Consul client used by Terraform backend (i.e. the `backend "consul" {}` block in Terraform `main.tf`).
2. Configuration values for Consul through ENV were not passed to the Consul client used by Terraform backend if a provider `task_env` was set because it no longer consumed from the os environment ([tfexec docs](https://pkg.go.dev/github.com/hashicorp/terraform-exec@v0.13.0/tfexec#Terraform.SetEnv)).
The …
=> Use consul configuration for the default consul backend for Terraform

api/api_test.go, api/client.go, api/client_test.go, api/task.go, api/task_test.go, command/task_enable.go, e2e/api_test.go
While writing the API docs for Update Task, I found that the returned response didn't make sense to me for all cases
PR changes the response so that the returned driver.InspectPlan is wrapped in an 'inspect' object, and it is only returned when `?run=inspect` is requested.
For other/no run options, return an empty 'inspect' object. Previously, an empty driver.InspectPlan was returned when `?run=inspected` was _not_ requested. The empty values are confusing. In particular, `changes_present` would be false for `?run=now` even though changes might have actually been present.
Example payload when `?run=inspect`
```
{
"inspect": {
"changes_present": true,
"plan": "<Terraform plan output>"
}
}
```
Payload when no run option or `?run=now`
```
{}
```
Prior to the change, payload when payload when …
=> Modify the Update Task API response when returning inspect

docker/Dockerfile
Changed /consul-terraform-syn directory to be owned by the added user of
the same name and made it the working directory. This allows writing to
the current/working directory which is needed for the sync-tasks
directory to be created and for terraform to be downloaded locally (both
the defaults).
Note that setting the terraform config variables 'path' or 'working_dir'
to something other than "" will not work.
=> fix docker permissions with a 'home' directory

api/api_test.go, api/client_test.go, driver/terraform_test.go, e2e/api_test.go, e2e/command_test.go, e2e/e2e_test.go, templates/tftmpl/integration_test.go, testutils/utils.go, testutils/utils_test.go
Commits:
- Update MakeTempDir() to have testing.T parameter and check for errors within
function rather than have the caller check errors
- Move registerService() to testutils.RegisterConsulService()
- Move apiRequest() to testutils.RequestHTTP(). Update other http requests in
tests to use testutils function
- Add some comments to some public structs/methods
=> Refactor testutils functions

api/api.go, api/api_test.go, api/client_test.go, api/overall_status.go, api/overall_status_test.go, api/task.go, api/task_status.go, api/task_status_test.go, api/task_test.go, controller/controller.go, controller/readonly.go, controller/readwrite.go, driver/drivers.go, driver/drivers_test.go
A map of drivers is shared across the API handlers and read-write controller
to manage task lifecycle. This map of drivers is currently used with read-access
only. However, we will want to support write-access in order to support a
create task cli and delete task cli.
Drivers structure will wrap the map of drivers in order to manage concurrent
read/write access to the map.
Changes:
- Add driver.Drivers{} to replace map[string]driver.Driver
- New methods to support currently required functionality NewDrivers(),
drivers.Add(), drivers.Get(), drivers.Map()
=> Refactor map of drivers to a Drivers object

api/task_status.go, api/task_status_test.go, event/store.go, event/store_test.go
Previously when requesting task status for a task with a driver and no events (e.g. a task configured as disabled), the API would return:
```
TaskStatus{
TaskName:  "task_d",
Status:    StatusUnknown,
Enabled:   false,
Providers: []string{}, // this data is missing
Services:  []string{}, // this data is missing
EventsURL: "",
},
```
It should return:
```
TaskStatus{
TaskName:  "task_d",
Status:    StatusUnknown,
Enabled:   false,
Providers: []string{"null"},
Services:  []string{"local"},
EventsURL: "",
},
```
See test for more details.
Commits:
- Fix how store.Read() returns events for tasks without events. This was causing tasks without events to be handled similarly as tasks with events. Therefore code handling tasks without events was unreachable
- After fixing store.Read, update code …
=> Fix bug in Task Status API response when requesting task with no events

go.mod, go.sum
Filtering service tag that contained `=` was supported in techpreview2 and broke in beta.
tags.hcl config
```hcl
service {
name = "my-app"
tag = "my=tag"
}
task {
name = "test"
services = ["my-app"]
source = "findkim/print/cts"
}
```
```
$ consul-terraform-sync -inspect -config-file ./configs/tags.hcl
2021/03/11 16:58:19.758458 [ERROR] (driver.terraform) checking dependency changes for 'test': execute: template: 3117340e9c3d7ed273cb6efc04266975:11:17: executing "3117340e9c3d7ed273cb6efc04266975" at <service "my-app" "\"my=tag\" in Service.Tags">: error calling service: health.service: invalid query parameter: "\"my=tag\" in Service.Tags" for "my-app"
```
Pulls in changes from https://github.com/hashicorp/hcat/pull/38 that fix the bug
=> Fix service tag erroring on '='

docker/docker-entrypoint.sh
Currently when running CTS docker container in once-mode or inspect-mode,
everything runs great. When running the container in daemon-mode (without any
flags), the configuration files are not passed in. In other modes (with flags), the
configuration file is successfully passed in.
The following error is seen when running`$ docker run -ti -v /my/path/to/config/file:/consul-terraform-sync/config hashicorp/consul-terraform-sync:0.1.0-beta`
> [ERR] config file(s) required, use --config-dir or --config-file flag options...
Change: update docker entrypoint to also pass config-directory when no CTS flags
are passed. With this change, I was able to build the docker image locally and test
daemon-mode, version, once-mode successfully
=> Fix "missing config flag option" when running docker container in daemon-mode

e2e/api_test.go, e2e/benchmarks/tasks_test.go, e2e/command_test.go, e2e/config.go, e2e/e2e_test.go, testutils/consul.go
Updates the E2E tests to connect with the Consul agent over HTTP/2 by enabling TLS (go limitation).
Since the test setups now require HTTPS endpoint and the cert path from the server to configure CTS, I refactored the config test setup to be more modular. Each test can now compose the pieces together to build the configuration for testing. This was in preference of not passing the test Consul server to all of the config helpers to access the cert path.
=> update e2e tests to utilize http2 enhancement

command/cli.go, command/commands.go, main.go
This lets us import the cli and use it to run cts similar to the e2e
tests, runs the full app, but keeping it in process. This is
particularly useful for benchmarking, so we can profile the benchmarks.
=> move cli.go into commands package

command/cli.go
cli.Run() takes the cli argument list as its argument... but then
ignores it and uses os.Args (which is what is passed from the call in
main).
Using the passed in arguments is required for testing.
=> use passed in args instead of os.Args

.github/CODEOWNERS
Documentation on how this works.
https://help.github.com/articles/about-codeowners/
=> make api-tooling-core team the default reviewer

controller/readwrite.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/benchmarks/tasks_test.go, testutils/utils.go
```
$ go test ./e2e/benchmarks/ -bench=BenchmarkTasksConcurrent -tags e2e
BenchmarkTasksConcurrent_t01_s50/task_setup-8                10   0.109 s/op
BenchmarkTasksConcurrent_t01_s50/once_mode-8                 1    4.088 s/op
BenchmarkTasksConcurrent_t01_s50/task_concurrent_execution-8 1    1.470 s/op
BenchmarkTasksConcurrent_t02_s50/task_setup-8                5    0.225 s/op
BenchmarkTasksConcurrent_t02_s50/once_mode-8                 1    7.846 s/op
BenchmarkTasksConcurrent_t02_s50/task_concurrent_execution-8 1    2.259 s/op
BenchmarkTasksConcurrent_t10_s50/task_setup-8                1    1.082 s/op
BenchmarkTasksConcurrent_t10_s50/once_mode-8                 1    40.023 s/op
BenchmarkTasksConcurrent_t10_s50/task_concurrent_execution-8 1    3.973 s/op …
```
=> Add benchmark tests for concurrent task execution emulating daemon mode

testutils/sdk/sdk.go, testutils/utils.go
Several TestServer methods still require *testing.T as the argument
which makes them unusable from a benchmark. This copies the one
remaining method we use (and it's supporting code) from the sdk into
testutils/sdk/. The only changes made were to change the *testing.T to
testing.TB and the smallest transformation possible to convert things
from private methods to local functions.
Once a new version of Consul's SDK is released (current is 0.7.0) we can
dump this and switch back as they've already excepted a PR to fix the
*testing.T issue and we are just awaiting the (unscheduled) release.
=> workaround consul/sdk's TestServer benchmark issue

retry/retry.go, retry/retry_test.go
Previous "exponential" backoff algorithm was `x**2`, which is incorrect. Adjusted
to be actually exponential:`2**x`
=> Fix exponential backoff calculation for retry methods

e2e/benchmarks/services_test.go, go.mod, go.sum
Runs benchmarks using the Null provider and working with Consul setup
with multiple Services or Service Instances.
Currently uses HTTP connections as they are faster and we aren't using a
lot of connections.
=> add null provider services/instances benchmarks

e2e/tasks_test.go, go.mod, go.sum, testutils/utils.go
Resolves #234
Pulls in update from https://github.com/hashicorp/hcat/pull/40 which fixes multiple templates getting removed after second render. That had caused some tasks to go stale and not update as catalog changes were detected by CTS.
Added e2e test that verifies content of `terraform.tfvars` after Catalog changes are detected and task execution is triggered. The new test fails w/o the hashicat changes.
```
--- FAIL: TestTasksUpdate/deregister_service (10.06s)
tasks_test.go:120: 
Error Trace:	tasks_test.go:120
Error:      	Not equal: 
expected: []string{"api", "web", "web_new"}
actual  : []string{"api", "api_new", "web", "web_new"}
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,4 @@
-([]string) (len=3) {
+([]string) (len=4) {
(string) (len=3) "api",
+ (string) (len=7) "api_new",
(string) …
```
=> Fix multiple tasks not triggered on same service

command/cli.go, version/version.go
CTS versions 0.1.0-techpreview2 and 0.1.0-beta output excluded the CLI name due to the build process not setting it. We likely missed this because the local development build process using the [Makefile set the name](https://github.com/hashicorp/consul-terraform-sync/blob/master/Makefile#L26).
```
$ consul-terraform-sync -version
0.1.0-techpreview2 (d844653)
Compatible with Terraform >= 0.13.0, < 0.15
```
should be
```
$ consul-terraform-sync -version
consul-terraform-sync 0.1.0-techpreview2 (d844653)
Compatible with Terraform >= 0.13.0, < 0.15
```
not going to back port this, fixing for 0.1.0 GA and beyond
=> Default version name

e2e/benchmarks/task_trigger_test.go
2.5s from when Catalog changes are detected to re-rendering the `terraform.tfvars` file before Terraform commands are executed on the workspace. The benchmark is testing with the task buffer period disabled. The 2.5s includes the added 1s delay to mitigate race condition (context https://github.com/hashicorp/consul-terraform-sync/pull/232#pullrequestreview-621647245)
```
$ go test ./e2e/benchmarks/ -bench BenchmarkTaskTrigger -benchtime=10s -tags e2e
[INFO] freeport: detected ephemeral port range of [49152, 65535]
[INFO] freeport: reducing max blocks from 30 to 26 to avoid the ephemeral port range
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/consul-terraform-sync/e2e/benchmarks
BenchmarkTaskTrigger-8   	       6	2507039392 ns/op
PASS
ok …
```
=> Add benchmark for task to be triggered

controller/readwrite.go, controller/watcher.go, e2e/benchmarks/services_test.go, e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/benchmarks/tasks_test.go, e2e/e2e_test.go, go.mod, go.sum, retry/retry.go, retry/retry_test.go, testutils/consul.go
When hcat polls Consul for changes in Consul catalog, it will now retry on error. It will retry a maximum of 9 times with exponential backoff. 9 retries with some jitter totals to waiting 8.5-12.8 minutes. If after 9 retries there is still an error, then CTS will exit.
Commits (see commit message for more details)
- Make retry package's waitTime() public
- Configure hcat watcher with a Consul retry function (this consumes retry.WaitTime()) (modified in last commit)
- Pull latest hcat version
- Update CTS to exit when hcat watcher errors since there is a retry now
- Refactor testutils for changes needed to write a Consul restart e2e test
- Consul restart e2e test
- Update naming and comments for clarity
Resolves: https://github.com/hashicorp/consul-terraform-sync/issues/233
=> Add retry when hcat connection with Consul has an issue

e2e/api_test.go, e2e/benchmarks/services_test.go, e2e/command_test.go, e2e/config.go, e2e/e2e_test.go, e2e/tasks_test.go, e2e/test_modules/e2e_basic_task/main.tf, templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, testutils/consul.go, testutils/cts.go, testutils/utils.go
These functions will be shared with the compatibility test (separate PR) which I want to put in a separate package from the other e2e tests. This PR refactors/cleansup a lot of e2e functions to testutils so that they can be used across package.
Note: made changes to benchmark tests. Ran the "lowest" benchmark test for each type of test to confirm still working.
Changes: (see commit for more details)
- Update module to generate shorter textfile name
- Refactored functions into testutils.CheckDir
- Refactored functions into testutils.CheckStateFile (fixed issue later commit)
- Refactored functions into testutils.WriteFile (fixed issue later commit)
- Refactored functions into testutils.CheckFile (fixed issue later commit)
- Refactored functions into testutils.StartCTS
- Update a test with a …
=> Refactor e2e functions to testutils

.circleci/config.yml, Makefile, go.mod
The recent 0.1.0 Beta and GA releases were compiled using go 1.16.
Go version was not consistent between go.mod, CI testing, and release.
=> Consistent on go 1.16

e2e/compatibility/consul_test.go
Initial work for running Consul compatibility testing for OSS GA releases for the highest patch version given a major + minor version. 
Note:
- Does not test datacenter-related compatibility
- Is not run automatically in CircleCI with e2e tests (separate compatibility directory) since this test takes a long time. Definitely room for improvement on selecting specific Consul versions to test and parallelizing tests within a version.
=> Add e2e for testing theoretical Consul compatibility

.circleci/config.yml, Makefile
Update the benchmark to run weekly instead of nightly
The weekly CI job will appear on the master branch checks on Wednesday at 2:10 UTC every Wednesday. Results are formatted in json and can be found under the “artifacts” tab -> benchmarks.json.
=> Weekly benchmark

.github/workflows/backport.yml
This adds [backport-assistant](https://github.com/hashicorp/backport-assistant) as a Github Action to enable backport/* label automation
TODO: When this is merged, add `ELEVATED_GITHUB_TOKEN` secret
=> Enable backport/* label automation

e2e/e2e_test.go
Recently the `TestE2ERestartConsul` has been intermittently failing ([ex](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/876/workflows/714e38e5-7551-4243-9f14-6a86027a2d92/jobs/1719)). Replicating
locally, failures seems to be consistently caused by a connection-refused error
when CTS tries to create a terraform workspace for the task (truncated):
```
[INFO] running Terraform command: terraform workspace new -no-color e2e_task_api_db
Failed to get configured named states: Get "https://127.0.0.1:47503/v1/kv/consul-terraform-sync/terraform-env:?keys=&separator=%2F": dial tcp 127.0.0.1:47503: connect: connection refused
[ERR] (client.terraformcli) unable to create workspace: "e2e_task_api_db"
[ERR] (driver.terraform) error initializing workspace, skipping apply for …
```
=> Increase wait time on E2E test on restarting Consul

config/condition.go, config/condition_catalog_services.go, config/condition_catalog_services_test.go, config/condition_services.go, config/condition_services_test.go, config/condition_test.go, config/config.go, config/config_test.go, config/task.go, config/task_test.go, config/testdata/long.hcl, config/testdata/long.json
Currently tasks run depending on service changes. We want to start supporting a
new feature where tasks can be configure to run depending on different
conditions. For the feature, we will add a condition configuration that allows
different condition types. The default type is the current run condition,
service changes.
Commits (see message for more details)
- Add ConditionConfig interface and ServicesConditionConfig{} (default)
- Add CatalogServicesConditionConfig{}
- Update TaskConfig with new Condition field
- Update configuration decoding to support ConditionConfig
=> Support condition config in task blocks

api/client.go, api/client_test.go, e2e/api_test.go, e2e/command_test.go, e2e/compatibility/consul_test.go, e2e/config.go, e2e/e2e_test.go, e2e/tasks_test.go, testutils/cts/cts.go
Flakey tests due to sleep times had us increasing them every so often. It seems sensitive to the load of the machine and changes to the underlying CTS logic. The new CTS client method allows the test to configure the max timeout
waiting for the API to start up and not have to wait the full duration. The API availability determines that CTS has completed executing the tasks once through successfully.
Reduces the e2e CI job from 2m to 1m32s
=> Update e2e tests to poll API availability

command/cli.go
Inspect mode was being logged as daemon mode. In report it was requested
to be reported as inspect mode, so went with that.
This also collects the log output line for each mode into 1 place. To
make it easier to find and more consistency in when mode log line is output.
Fixes #211
=> fix inspect mode log output

controller/watcher.go
Consul's retries were logging every retry for every watched field. It
was very verbose. This quiets it down by changing all the retry logs to
DEBUG level except for the last one which is (unchanged from) ERR level.
Fixes #260
=> all but last consul retry log set to DEBUG level

examples/sync-tasks/my-task/terraform.tfvars, examples/sync-tasks/my-task/terraform.tfvars.tmpl, templates/tftmpl/testdata/only_api_service.tfvars, templates/tftmpl/testdata/only_web_service.tfvars, templates/tftmpl/testdata/terraform.tfvars, templates/tftmpl/testdata/terraform.tfvars.tmpl, templates/tftmpl/tfvars.go
This updates the CTS generated Terraform variables to use the suggested format from the documentation instead of `key : value`. No breaking change, but all generated templates and tfvars will be re-rendered with `=` now.
https://www.terraform.io/docs/language/expressions/types.html#maps-objects
> Maps/objects are represented by a pair of curly braces containing a series of `<KEY> = <VALUE>` pairs:
```hcl
services = {
"api.worker-01.dc1" = { }
}
```
=> Update tfvars map to use "key = value"

docker/Dockerfile
This adopts the new HashiCorp PGP key, as described at https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2 and https://hashicorp.com/security.
Please merge after reviewing 🙏
=> Adopt new pgp key

driver/terraform_download.go
Terraform 0.13.7 was just released with the rotated HashiCorp GPG signing key
used for provider package verification ([HCSEC-2021-12](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512)). Update CTS's fallback 
version of Terraform to this release.
=> Update fallback Terraform version from 0.13.5 to 0.13.7

.gitignore, api/api_test.go, e2e/api_test.go, e2e/benchmarks/services_test.go, e2e/benchmarks/tasks_test.go, e2e/compatibility/consul_test.go, e2e/condition_test.go, e2e/config.go, e2e/render_test.go, e2e/tasks_test.go, examples/runnable-example/config.hcl, templates/tftmpl/root.go, templates/tftmpl/root_test.go
**Breaking Change:**
When using a local module for a task, the relative path provided as the source is now based on the working directory of CTS. Previously, the path was based on the task directory (e.g., `sync-tasks/<task-name>`).
Operators with tasks that use local modules will need to update the task's source variable. For example, when running CTS with the following directory structure:
```
.
| -- config.hcl
| -- my-local-module/
| -- sync-tasks/example-task  
```
Previous to this change, the source would have been specified as follows:
```hcl
task {
name = "example-task"
description = "this task prints output and creates files with content"
source = "../../my-local-module"
services = ["api", "web"]
}
```
With this change, the source needs to be updated to:
```hcl
task {
name = …
```
=> Update expected relative path of task source for local modules

Makefile, driver/terraform.go, e2e/condition_test.go, go.mod, go.sum, mocks/templates/template.go, templates/hcat.go, templates/tftmpl/notifier/notifier.go, templates/tftmpl/notifier/notifier_test.go
For the catalog-services condition, we only want service [de]registration
changes to trigger tasks. Currently health services changes and catalog service
tag changes can additionally trigger tasks.
Commits:
- Pull latest hcat Notify() which will allow CTS to write custom notifications
- Add new notifier for catalog-services condition that will only notify (and
therefore only trigger) on service [de]registration
- Increase e2e timeout
=> Catalog service registration notifier to suppress non-registration changes

client/terraform_cli.go, client/terraform_cli_test.go, examples/reference-example/example-config.hcl
Expands relative paths to full paths for the task variable files 
to support both relative and full paths.
Closes https://github.com/hashicorp/consul-terraform-sync/issues/279
=> Support relative paths for task variable files

controller/controller.go, controller/controller_test.go, driver/driver.go, driver/terraform.go, driver/terraform_test.go, mocks/driver/driver.go, templates/tftmpl/golden_test.go, templates/tftmpl/integration_test.go, templates/tftmpl/root.go
The force parameter for `driver.InitTask` is only used for testing and was prematurely added. Updated the signature to remove `force` and be consistent to accept `context`.
=> Update driver interface

driver/terraform.go, templates/tftmpl/notifier/notifier.go, templates/tftmpl/notifier/notifier_test.go
Once-mode requires all dependencies to be retrieved before sending a
notification to CTS to render the complete template and execute the task.
A task has a template which can have multiple types of dependencies. A task configured with
catalog-service condition will only notify on a catalog-service type dependency changes and
not on other types of dependency changes.
During once-mode, the template dependencies are received asynchronously and therefore
can cause a race:
- If catalog-service dependency is received last: this is fine with once-mode i.e. all
dependencies are received, notification is sent, task is executed
- If a different dependency is received last: no notification is sent because only catalog-service
dependencies send notification. However, once-mode is waiting for all the …
=> Fix catalog-service race condition during once-mode

api/test.go, e2e/config.go
Sometimes e2e tests fail in CircleCI and are not reproducible locally.
Currently no e2e logs are outputted in Circle since the tests are run in
parallel making the logs interwoven and undecipherable.
Change: when CTS stops and tests have failed, output a snippet of the CTS logs.
Update e2e default log-level to DEBUG since we will likely be debugging when
these logs are outputted.
Sample output for a failed test
=> Print out log snippet when CTS fails in e2e tests

api/test.go, e2e/api_test.go, e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/command_test.go, e2e/compatibility/consul_test.go, e2e/condition_test.go, e2e/e2e_test.go, e2e/tasks_test.go, templates/tftmpl/integration_test.go, testutils/consul.go, testutils/utils.go
In our e2e tests, there are a lot of `time.Sleep()`s used to wait for a Consul service to register and for CTS to trigger and finish in response to a change. These sleeps can sometimes cause tests to flake and are an arbitrarily long value that cause our tests to sometimes be longer than needed.
Currently, this has a minor improvement on the e2e CI job time. It reduces from ~1min 30-50s to ~1min 10s. However, this change's original intention was for an upcoming e2e test that causes the e2e test suite to timeout. This change reduces this upcoming test's length and prevents it from causing the e2e suite timeout.
Commits:
- Add new WaitForEvent which polls CTS for triggering
- Update RegisterConsulService to poll for the service to be registered
- Update e2e test sleeps with latest …
=> Update e2e test to poll for Consul service registration and CTS events

config/terraform.go, config/terraform_test.go
Fixes the issue where if the path was an empty string, Terraform would be installed in
a temporary directory, but CTS expected the binary to be in the current working directory.
This aligns now with the behavior for when no path is provided.
Closes https://github.com/hashicorp/consul-terraform-sync/issues/212
=> Set Terraform path to working directory if empty string

Makefile, templates/tftmpl/condition.go, templates/tftmpl/integration_test.go, templates/tftmpl/module_variables.go, templates/tftmpl/root.go, templates/tftmpl/tfvars.go, templates/tftmpl/variables.go, testutils/consul.go
The newline changes don't effect the end result, but changes the extra newlines to be added by the caller instead of included in the template bits inconsistently.
The second commit around Condition interface is more of an opinionated change to group all condition related stuff to the Condition types instead of each file template managing the different condition template/generated code independently. Lmk if you prefer for me to leave out the second commit.
=> Template newlines and expand tftmpl.Condition interface

client/terraform_cli.go, client/terraform_cli_test.go, e2e/e2e_test.go, e2e/test_modules/incompatible_w_cts/main.tf, e2e/test_modules/incompatible_w_cts/variables.tf
Also fixes the error message which did not work for TF v0.13 and v0.14 because they did not return the context. I also realized the context was showing the task name and not the module name anyway, so this new message is more informative either way.
- Add e2e test so that if the error messages changes in newer versions of terraform, we will know to adjust accordingly
- Updated error message to determine task name from current workspace and improve some formatting
- Assert that specific error message is returned in unit test
- Include entire validate output in unit test (previously was just the info we cared about)
- Add test cases to unit test for both v0.13/v0.14 and v0.15 outputs
=> E2E test for parsing Terraform validate

config/service.go
Tag will be removed in v0.4.0 (https://github.com/hashicorp/consul-terraform-sync/issues/312).
=> Update tag deprecation warning with planned removal version

e2e/condition_test.go, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/catalog_services_registration_test.go
Changes:
- Add testing for various query parameters for Fetch()
- Catch a regexp nil-pointer edge-case from testing (regexp can't be nil when running
CTS e2e)
- Remove e2e test that was only able to test node-meta query parameter
filtering and was over-scoped (also unnecessarily tested triggering)
Context: addresses's @ findkim comment that testing node-meta as an e2e test was
overscoped and that the main test case is around query filtering (thanks!) https://github.com/hashicorp/consul-terraform-sync/pull/278#discussion_r631158825
=> Test for CatalogServicesRegistrationQuery query parameter filtering in Fetch()

controller/controller.go, controller/controller_test.go, controller/readwrite_test.go, driver/driver.go, driver/terraform.go, driver/terraform_test.go, mocks/driver/driver.go
We determined that not all drivers may have a validate method, so removed validate
task from the interface and made it part of the Terraform driver InitTask method.
Also moves workspace initialization to InitTask and remove it from apply/inspect/validate.
New output:
```
2021/06/16 17:14:43.618472 [ERR] (ctrl) error initializing task "test-task"
2021/06/16 17:14:43.618496 [ERR] (cli) error initializing controller: 
module for task "test-task" is missing the "services" variable
module for task "test-task" is missing the "catalog_services" variable, add to module or set "source_includes_var" to false
```
=> Move validate call to be part of task initialization

api/server_test.go, config/config.go, config/config_test.go, config/driver_test.go, config/task.go, config/task_test.go, config/terraform.go, config/terraform_test.go, controller/controller.go, controller/controller_test.go, driver/task.go, driver/terraform.go, driver/terraform_download.go, driver/terraform_test.go, e2e/render_test.go
The working directory is more associated with each task and its Terraform workspace than the driver.
Related #314
=> Deprecate driver.working_dir in preference for global working_dir

.circleci/config.yml
Benchmarks are currently failing weekly. Disabling until we can prioritize
looking into why it is failing
=> Temporarily disable benchmarks

config/config_test.go, config/task.go, config/task_test.go
The Terraform Cloud API allows configuring the Terraform CLI version for each workspace. A new option is being added to CTS enterprise to independently configure the TF version per task. The PR adds a user-friendly error to CTS OSS when trying to use an enterprise configuration option.
```
2021/07/06 14:56:09 [ERR] (cli) error validating configuration: unsupported configuration 'terraform_version' for task "test". This option is available for Consul-Terraform-Sync enterprise when using the Terraform Cloud driver, or configure the Terraform client version within the Terraform driver block
```
Related #327
=> Add error when setting terraform_version config option per task in OSS

driver/terraform.go, e2e/api_test.go, templates/tftmpl/root.go, templates/tftmpl/root_test.go
The logic for converting the relative path to an absolute path is specific to
the Terraform driver, so moving it from the template code.
=> Handle local module source relative paths in Terraform driver

api/client.go, api/task.go, api/task_test.go
When client connection closes, the server would still attempt process the request to completion. Changes allow server to error and exit early
=> Fix handler to use http.Request context to react to client connection

command/cli.go, controller/controller.go, controller/controller_test.go, controller/readonly.go, controller/readwrite.go, controller/readwrite_test.go, e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/render_test.go
The API contains identical objects as the controller and is
dependent on it. This proposes to move the API server to the
controller to keep controller details out of the main function:
drivers and event.Store
=> Refactor API server to stem from controller

controller/controller.go, controller/readonly.go, controller/readonly_test.go, controller/readwrite.go, controller/readwrite_test.go, driver/drivers.go
Units became a redundant abstraction with the usage of drivers
=> Remove intermediate struct units

api/client.go, api/task.go, controller/controller.go, controller/controller_test.go, controller/readwrite.go, driver/drivers.go, driver/terraform.go, e2e/config.go
An API request to update a task would race against the controller's main go routine and eventually caused a deadlock for the specific edge case when a task with multiple services starts off disabled and then is enabled via CLI/API.
My understanding of the root cause: On enabling, this would be the first time the task is run. The API request would initialize the template and wait for the template to fetch all dependencies. Meanwhile the controller gets notified on those dependency changes and then also attempt to render that same template. The API request is waiting for the controller/watcher to process the dependencies and mark that template as dirty. But that controller routine waits indefinitely for the lock that the API request had obtained and cannot proceed to call watcher.Wait in …
=> Fix update race bug

config/config.go, config/decode.go, config/decode_test.go
The mapstructure error is not intuitive to interpret when a user configures repeated blocks for a configuration that is not supported.
With the same config file `test.hcl`
```
log_level = "DEBUG"
consul {}
consul {}
```
Current error
```
$ consul-terraform-sync -inspect -config-file test.hcl
2021/07/27 16:50:02 [DEBUG] (config) mapstructure decode failed
2021/07/27 16:50:02 [ERR] (config) failed decoding content from file: test.hcl
2021/07/27 16:50:02 [ERR] (cli) error building configuration: 1 error(s) decoding:
* 'consul' expected a map, got 'slice'
```
New error
```
$ consul-terraform-sync -inspect -config-file test.hcl
2021/07/27 16:50:44 [DEBUG] (config) mapstructure decode failed
2021/07/27 16:50:44 [ERR] (config) failed decoding content from file: test.hcl
2021/07/27 16:50:44 [ERR] …
```
=> Add config decode error wrapper

.circleci/config.yml, e2e/benchmarks/services_test.go, e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/benchmarks/tasks_test.go, e2e/render_test.go, testutils/consul.go
- Fixes issues for when parts of tests are run multiple times
- Add a dependency change before a run
- Reinitialize the controller context per run
- Remove the multiple calls of the Once method
- Enables benchmarks and adds a CircleCI step to print out just the results of the benchmarks without other logs
- Fixes some instances where the temporary directory wasn't being used for the tasks 
- Updates Consul services names to prevent warning log
For context, benchmarks were failing because of issues when parts of the tests were run multiple times. For example, a run might pass the first time because previously there was a change in a dependency, but on the second run, there would have been no change. The tests would then hang indefinitely on that second run, waiting for a dependency change. …
=> Fix and enable benchmarks

command/cli.go, config/consul.go, config/terraform_test.go, docker/Dockerfile, docker/README.md
Adds run instructions for docker container and build instructions for the docker image.
PR includes other small quality of life improvements I stumbled upon:
* Bugfix: Consul address env was never read because a default was set.
* Improve Dockerfile required argument to have a default name since `consul-terraform-sync` is expected in the entry script.
* Changes the order of installing Terraform only after the Consul connection has been tested to fail earlier and faster.
=> Docker docs

driver/task.go, e2e/condition_test.go, templates/tftmpl/condition.go
Updated services condition to use SourceIncludesVar to determine whether
to set the template as the services variable, similar to how catalog
condition sets the catalog_services variable. For the Terraform driver,
this is always going to be set to true.
Related to https://github.com/hashicorp/consul-terraform-sync/issues/299
=> Refactor services condition to more standard pattern

.github/workflows/build.yml
Fixing the package names for linux/386 as we were getting:
=> fixing package names

.github/scripts/generate_metadata.sh, .github/workflows/build.yml, .release/ci.hcl, .release/docker/Dockerfile, .release/docker/Makefile, .release/docker/docker-entrypoint.sh, Makefile, build-scripts/version.sh, version/version.go
**Enabling the CRT CD pipeline for CTS.**
Final "green" pipeline is [here](https://github.com/hashicorp/consul-terraform-sync/actions/runs/1186508858) 
This includes files and logic to build all binaries, docker images and rpms/debs and attach to the GitHub workflow.
The [promotion](https://github.com/hashicorp/crt-workflows-common/actions) pipeline will then kick off to sign/notarize and move these artifacts to the [stable](https://artifactory.hashicorp.engineering/ui/repos/tree/General/hashicorp-crt-stable-local%2Fconsul-terraform-sync%2F0.3.0%2Fc6c834563b4db401645738d7b4a3023a26a158bd) repo in Artifactory ready to be released.
We should have 25 artifacts in total:
consul-terraform-sync-0.3.0.arm64.rpm
consul-terraform-sync-0.3.0.x86_64.rpm
consul-terraform-sync-0.3.0.armelv5.rpm …
=> enabling CRT for consul-terraform-sync

config/condition.go, config/condition_consul_kv.go, config/condition_consul_kv_test.go, config/condition_test.go, config/task.go, config/task_test.go
Supports consul-kv condition in task block, where path is
a required attribute for the condition.
**Example Configuration:**
```
task {
...
condition "consul-kv" {
path = "test"
source_includes_var = true
recurse = true
datacenter = "dc1"
namespace = "test-namespace"
}
...
}
```
This PR only has the configuration changes. Follow up PR will have the template and notifier changes that use the configuration.
Part of https://github.com/hashicorp/consul-terraform-sync/issues/150
=> Add configuration for consul-kv condition

controller/readwrite.go, controller/readwrite_test.go, driver/drivers.go, e2e/benchmarks/tasks_concurrent_test.go
Once mode should not call an extra Watcher.WaitCh() which could
inadvertantly mute the first trigger after Once mode has completed
from when Run expects it.
Also improve taskNotify by simplifying how to enable for tests
=> Add unit test running Once and Run to test Watcher semantics

driver/task.go, go.mod, go.sum, templates/tftmpl/condition_consul_kv.go, templates/tftmpl/condition_consul_kv_test.go
Adds the templating work for Consul KV triggers, using the latest hcat changes for `key`, `keyExists`, and `keys`. The recurse option determines whether to use `keys` or `keyExists` + `key`. This is because of the Consul client used by hcat has a get method for `recurse=false` and a separate list method for `recurse=true`.
Follow up PR will have the notifier changes so that only KV dependencies trigger tasks and the end-to-end tests.
Part of https://github.com/hashicorp/consul-terraform-sync/issues/150
=> Consul KV condition template

config/condition.go, config/condition_schedule.go, config/condition_schedule_test.go, config/condition_test.go, config/task.go, config/task_test.go, go.mod, go.sum
Supports configuring a task with a schedule condition allowing users to
configure a task that monitors services in task.services but only execute
on a configured schedule rather than be dynamically triggered on changes.
Details:
- schedule condition's cron field is required
- uses the hashicorp fork of `cronexpr` to validate cron expression
- disables buffer_period and logs a warning if task's buffer_period is
configured. buffer_period does not make sense to be enabled for a scheduled
task
Example config:
```
task {
name = "scheduled_task"
description = "run task every 10 seconds"
services = ["web", "db"]
source = "path/to/module"
condition "schedule" {
cron = "*/10 * * * * * *"
}
}
```
Part of: https://github.com/hashicorp/consul-terraform-sync/issues/308
Subsequent prs
- Consume …
=> Add schedule task condition configuration

.github/workflows/build.yml
Removing arm/v5/v6 support from build.yml
Succesful run[ is here ](https://github.com/hashicorp/consul-terraform-sync/actions/runs/1211431864)
=> Remove arm/v5/v6 from build.yml

driver/terraform.go, driver/terraform_test.go, mocks/templates/watcher.go, templates/hcat.go
Benchmarks were failing when b.N > 1 with "duplicate watcher registry entry". `InitTask` could be called more than once and so adding the registry check would help for the benchmark and edge cases around task updates via the API in the future.
```
$ go test ./e2e/benchmarks -bench=BenchmarkTasks_t01_s01/ReadOnlyCtrl/task_setup -tags e2e -benchtime=3x
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/consul-terraform-sync/e2e/benchmarks
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
BenchmarkTasks_t01_s01/ReadOnlyCtrl/task_setup-8
--- FAIL: BenchmarkTasks_t01_s01/ReadOnlyCtrl/task_setup-8
tasks_test.go:79: 
Error Trace:	tasks_test.go:79
benchmark.go:192
benchmark.go:298
asm_amd64.s:1371
Error:      	Received unexpected error:
duplicate watcher registry entry
Test: …
```
=> Add watcher registration check to initTaskTemplate

e2e/e2e_test.go
The Terraform applies in CircleCI are sometimes taking longer than
expected, which is failing tests that start with multiple tasks.
=> Increase default API timeout in tests

.github/scripts/generate_metadata.sh, .github/workflows/build.yml
- crt cleanup includes fixing push event to only trigger on master and release branches
- Add new repo value to metadata - use PKG_NAME for artifact names (not repository name)
=> Crt cts cleanup

.release/README.md
This is adding a `README.md` to the `.release` directory that gives a high level overview of how to release with Common Release Tooling.
=> adding a README on how to release with CRT

CHANGELOG.md
Our new release process does not add the changelog date automatically. Manually changing afterwards.
For future release processes, we will need to change the date before the release if the process stays the same
=> Update CHANGELOG.md with 0.4.0 beta1 date

.circleci/config.yml
Followup to resolving the benchmarks failing https://github.com/hashicorp/consul-terraform-sync/pull/384
=> Add slack notification for benchmark failures

config/consul.go, config/tls.go, config/vault.go
TLS config loaded from env vars are different for Consul and Vault.
This reorganizes it to more easily be found in one place
=> Reorganize TLS finalize config

e2e/condition_consul_kv_test.go, go.mod, go.sum, templates/tftmpl/condition_consul_kv.go, templates/tftmpl/condition_consul_kv_test.go, templates/tftmpl/monitor_consul_kv.go, templates/tftmpl/notifier/consul_kv.go, templates/tftmpl/notifier/consul_kv_test.go
Having the two dependencies where the second dependency (the get) depends on the
value of the first dependency (if it exists) has made this too much of a special
case and adds too much complexity. Replacing with a single dependency keeps it
more in line with all our other templates.
=> Replace keyExists/key combination with keyExistsGet

docker/Dockerfile
3.13 had open security issues.
Changing to use the latest alpine:3 to better stay up to date.
Note alpine:3 is currently an alias for 3.14, which fixes the security issues.
=> update alpine version used in docker image

.circleci/config.yml
Adds slack notification for `unit_integration_tests` and `e2e_tests` when it fails on `main` and release branches.
https://circleci.com/developer/orbs/orb/circleci/slack
> `branch_pattern` - A comma separated list of regex matchable branch names. Notifications will only be sent if sent from a job from these branches. By default ".+" will be used to match all branches. Pattern must match the full string, no partial matches.
I don't know how to test this :(, so hopefully the format is correct for including the release branch regex
=> Add slack notification for failed CircleCI jobs on main

.circleci/config.yml, Makefile, e2e/compatibility/consul_test.go
Runs compatibility tests with Consul in parallel and adds it to weekly CI jobs.
* Fix tests looking for artifacts in old paths (missing task subdir)
* Refactor tests to run in parallel by version
* Reworked temp directories to not overlap across versions
Tests passing https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/1858/workflows/7185eedf-177e-4c37-9b61-0bb8a4690876/jobs/3655
TODO follow up and add Consul 1.11 when released.
I tried using hc-install library to fetch the latest version within minor releases, but it requires adding an internal dependency which would break builds for OSS users locally.
=> Weekly Consul compat tests

.circleci/config.yml
Updates binary versions used for CI testing for Consul, Vault, and Terraform
=> Bump latest versions for integration tests

Makefile
`git describe` fetches the latest tag based on the current branch.
The release process creates a tag off of release branches, which
are not associated with development branches like main or feature
branches. Running `make dev` would end up referencing an old tag
that predates the current release process.
The update to `GIT_DESCRIBE` now fetches the latest tag across all
branches.
Fixes `GIT_DESCRIBE` variable in Makefile
```
$ make dev
==> Installing consul-terraform-sync for darwin/amd64
$ consul-terraform-sync -version
consul-terraform-sync v0.1.0-345-g5ab7731 (4ca4743)
Compatible with Terraform >= 0.13.0, < 1.1.0
```
```
$ make dev
==> Installing consul-terraform-sync for darwin/amd64
$ consul-terraform-sync -version
consul-terraform-sync v0.4.0-beta1 (4ca4743 dirty)
Compatible with …
```
=> Fix Makefile dev version

e2e/benchmarks/benchmarks_test.go, e2e/compatibility/consul_test.go
Consul versions 1.5, 1.6 and 1.7 do not support the `-version` flag,
whereas all tested versions support the `version` subcommand
CTS is run directly via CLI or controller for benchmarks. It
does not properly setup log level and the logging is verbose and
pollutes the benchmark outputs that are stored as artifacts
=> Fix weekly ci

build-scripts/version.sh, version/version.go
So that we can set this to `ent` in the ENT repo's version_ent.go file.
This allows us more easily to construct true semver version numbers when doing pre-releases (version-prerelease+metadata) both for the human readable version and also for our build artifact versioning.
=> Add VersionMetadata field

.github/workflows/build.yml
Fixes build for docker images flagged in #474. This doesn't fix the 0.4.0 docker images yet though.
=> Set CGO_ENABLED=0

client/terraform_cli.go
Resolves #473
The `Snippet` object for this edge case revealed that not all diags include a context.
```
&{Context:<nil> Code:provider "null" {} StartLine:1 HighlightStartOffset:0 HighlightEndOffset:15 Values:[]}
```
```
2021-11-01T12:20:53.814-0500 [WARN]  client.terraformcli: Terraform validate returned warnings:
warnings=
| 
| warning: Empty provider configuration blocks are not required
| 
| on .terraform/modules/tf_validate_panic/main.tf line 1
| 1:provider "null" {}
| 
| Remove the null provider block from module.tf_validate_panic.
| To ensure the correct provider configuration is used, add null to the required_providers configuration
2021-11-01T12:20:53.814-0500 [INFO]  ctrl: driver initialized
2021-11-01T12:20:53.814-0500 [INFO]  ctrl: executing all tasks once through
```
=> Not all diagnostics include context

api/client.go, api/client_test.go, api/server_test.go, api/test.go, command/cli.go, command/meta.go, command/task_disable.go, command/task_enable.go, go.mod
Adds TLS flags to support TLS when using the CTS CLI
- TLS flags are passed via command line flags, or by environment variable
- command line flag values take precedence over corresponding environment variable values
- meta.go is responsible for handling flags set
- client.go handles environment variables and defaults required for creating the client
Example using flags:
```
consul-terraform-sync task enable \
-http-addr="https://localhost:8501" \
-ca-file="/Users/mwilkerson/dev/michael-cts-example/tls_consul.d/consul-agent-ca.pem" \
-client-cert="/Users/mwilkerson/dev/michael-cts-example/tls_consul.d/dc1-server-consul-0.pem" \
-client-key="/Users/mwilkerson/dev/michael-cts-example/tls_consul.d/dc1-server-consul-0-key.pem" \ 
example-task
```
Example using some environment variables (same …
=> Add tls cli client

api/test.go, e2e/command_test.go, e2e/config.go, e2e/utils.go
Added e2e testing for commands using mutual TLS (mTLS)
- TLS/mTLS flags are passed via command line flags, or by environment variable
- command line flag values take precedence over corresponding environment variable values
Example CTS Configuration:
```
tls {
enabled = true
cert = "/path/to/certs/localhost_cert.pem"
key = "/path/to/certs/localhost_key.pem" 
verify_incoming = true
ca_cert = "/path/to/certs/localhost_cert.pem"
}
```
Example CTS mTLS client using flags:
```
consul-terraform-sync task enable \
-http-addr="https://localhost:8501" \
-ca-cert="/path/to/certs/localhost_cert.pem" \
-client-cert="/path/to/certs/localhost_cert.pem" \
-client-key="/path/to/certs/localhost_key.pem"  \ 
example-task
```
Same example, this time using some environment variables
```
export …
```
=> Add e2e mtls tests

config/tls_cts.go, config/tls_cts_test.go
The go-rootcerts library has ca_cert take precedence over ca_path, so
calling out this behavior in a warning. Also fixes the mTLS check to look
for either ca_path or ca_cert, which was the original intent.
The diff isn't great to look at, but I moved one TLS check up further, modified the mTLS check to care about the CA options and not cert/key, and added the check that warns if both CA options are configured.
Warning will look like the following:
```
$ consul-terraform-sync --config-file=config.hcl
2021-11-10T11:57:44.155-0600 [WARN]  config: ca_cert and ca_path are both configured, but only ca_cert will be used
2021-11-10T11:57:44.156-0600 [INFO]  cli: v0.4.1 (5ff7739)
2021-11-10T11:57:44.156-0600 [INFO]  cli: running controller in daemon mode
```
=> Log warning if both ca_cert and ca_path are configured

Makefile
GitDescribe is no longer useful in the dev build because of how
the version prerelease and metadata are generated in conjunction
with different remotes. It pulls the latest tag across remotes even
though it's not relevant
```
% git remote -v
<remote>	git@github.com:hashicorp/<remote>.git (fetch)
<remote>	git@github.com:hashicorp/<remote>.git (push)
origin		git@github.com:hashicorp/consul-terraform-sync.git (fetch)
origin		git@github.com:hashicorp/consul-terraform-sync.git (push)
% git describe --tags `git rev-list --tags --max-count=1`
v0.4.1+ent
% consul-terraform-sync -version
consul-terraform-sync v0.4.1+ent (3e5a7ed)
```
With changes
```
% consul-terraform-sync -version
consul-terraform-sync 0.5.0-dev (3e5a7ed dirty)
Compatible with Terraform >= 0.13.0, < 1.1.0
```
=> Update Makefile dev build version

api/task_status.go
Because we weren't returning after an error was set, the response
code was attempted to be set again later, which caused "superfluous
response.WriteHeader call" errors to be logged. It also caused an
additional '{}' to be appended at the end of the response.
Previous Response:
```
$ curl -v localhost:8558/v1/status/tasks/nonexistent-task
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8558 (#0)
> GET /v1/status/tasks/nonexistent-task HTTP/1.1
> Host: localhost:8558
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Fri, 12 Nov 2021 21:30:16 GMT
< Content-Length: 66
<
{"error":{"message":"task 'nonexistent-task' does not exist"}}
{}
```
```
2021-11-12T15:30:16.461-0600 [INFO]  api: received request: …
```
=> Fix issue with response header when no task exists

e2e/command_test.go, e2e/config.go, e2e/utils.go, testutils/utils.go, testutils/utils_test.go
- Added test cases for both TLS and MTLS using CAPath instead of CACert. CAPath allows for a directory of certs to be passed to server and client instead of just a single file. Then the server and/or client is able to authenticate using the correct cert.
- Modified test cases so that they don't use self-signed certificates (CA and Cert being the same file). Instead using a CA, `localhost_cert.pem` and a cert signed by the CA, `localhost_leaf_cert.pem` which would be a more realistic scenario.
- Added testutil functions for copying test files to test directories. This was needed since CAPath requires that only certs (no keys, readmes, etc.) be in the provided directory.
Example CTS Configuration:
```
tls {
enabled = true
cert = "/path/to/certs/localhost_cert.pem"
key = …
```
=> Added new tests for CA path

config/decode.go, config/task.go
Update error line length to fit <80 chars
```
2021-11-17T11:17:55.413-0600 [ERROR] cli: error building configuration:
error=
| 'config.hcl' has invalid keys: driver.terraform-cloud
| 
| Terraform Cloud is a Consul-Terraform-Sync (CTS) Enterprise feature.
| Upgrade to Consul Enterprise to enable CTS Enterprise features.
```
=> Add config error for driver.terraform-cloud when using CTS OSS

config/condition.go, config/condition_services_test.go, config/condition_test.go, config/config_test.go, config/monitor_services.go, config/monitor_services_test.go, config/source_input.go, config/source_input_services_test.go, config/source_input_test.go, config/task_test.go, controller/controller_test.go
Update `condition "services"` and `source_input "services"` to support the same services filtering fields as supported in `services` block. Same default values as with `services` block.
- Namespace
- Datacenter
- Filter
- CTS User Defined Meta
Changes:
- Update struct with new fields
- Refactor tests for services condition, source input, monitor
- Update misc tests
Future PR to consume namespace, datacenter, filter, cts user-defined meta
Example usage:
```
source_input "services" {
regexp = ".*"
datacenter = "dc2"
namespace = "ns2"
filter = "some-filter"
cts_user_defined_meta {
key = "value"
}
}
```
```
condition "services" {
regexp = ".*"
datacenter = "dc2"
namespace = "ns2"
filter = "some-filter"
cts_user_defined_meta {
key = "value"
}
}
```
Part of …
=> Update Services Condition & Source Input configuration

driver/terraform.go, driver/terraform_test.go, e2e/condition_service_test.go, templates/tftmpl/tmplfunc/hcl_service_func.go, templates/tftmpl/tmplfunc/hcl_service_func_test.go, templates/tftmpl/tmplfunc/services_meta.go, templates/tftmpl/tmplfunc/services_meta_test.go, templates/tftmpl/tmplfunc/tmpl_func.go
Implement new field `cts_user_defined_meta`
Note:
- This is a parallel field to the existing `cts_user_defined_meta` in the `service` block
- Configuration added in earlier PR: https://github.com/hashicorp/consul-terraform-sync/pull/520
- New query fields implemented in earlier PR: https://github.com/hashicorp/consul-terraform-sync/pull/523
Changes:
- Update ServicesMeta to support both `cts_user_defined_meta` in the `service` block (existing) and in `condition "services"` new
- Update references to ServicesMeta
- Update driver to pass both types of metadata to template
- Test new `cts_user_defined_meta` in services condition e2e test
- Note: manually tested for services source input because source input is currently only supported with scheduled conditions. Adding testing for this to …
=> Implement Services Condition & Source Input MetaData field

driver/terraform.go, driver/terraform_test.go
Pass data in rather than retrieve from the receiver
=> Refactor getServicesMetaData no longer rely on TF driver

templates/tftmpl/integration_test.go
Ran the flakey test `TestRenderTFVarsTmpl` several times to fail and again with updates to check for flakeyness.
[CircleCI](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/2478/workflows/4d68035d-8290-4550-aa79-e9048627c210/jobs/5411)
```
go test ./templates/tftmpl -tags integration -count 10
```
The tests flake based on Consul information returned to CTS -- sometimes there are no tagged node address causing the test to fail which expects them.
[With the changes, i've ran it 50 times w/o fail](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync?branch=flakey-test)? my guess is running these in parallel slows down the tests for consul to get the full information
=> Flakey test

api/client.go, command/commands.go, command/meta.go, command/task_delete.go, command/task_enable.go, e2e/command_test.go
Adds the client and the CLI command for deleting a task.
**Example Outputs**
Happy path/approved
```
$ consul-terraform-sync task delete test-task
==> Do you want to delete 'test-task'?
- This action cannot be undone.
Only 'yes' will be accepted to approve.
Enter a value: yes
==> Deleting task 'test-task'...
==> Deleted task 'test-task'
```
Denied
```
$ consul-terraform-sync task delete test-task
==> Do you want to delete 'test-task'?
- This action cannot be undone.
Only 'yes' will be accepted to approve.
Enter a value: no
Cancelled deleting task 'test-task'
```
Task does not exist
```
$ consul-terraform-sync task delete nonexistent
==> Do you want to delete 'nonexistent'?
- This action cannot be undone.
Only 'yes' will be accepted to approve.
Enter a value: yes
==> Deleting task …
```
=> Delete Task CLI

api/api.go, api/handler.go, api/representation.go, api/representation_test.go, api/task.go, api/task_create.go, api/task_create_test.go, api/task_delete_test.go, api/task_test.go, controller/controller.go, controller/controller_test.go, controller/readwrite.go, e2e/api_test.go, testutils/utils.go
This PR covers some of the work for creating a new task
- Controller/controller.go does a lot of initial setup, to allow for this setup to be utilized later in the span of CTS's running lifespan, a new method is required which can create a task driver based on a task config. `createNewTaskDriver`
- Refactor controller to use `createNewTaskDriver` when initializing the controller when CTS starts up
- Create a handler for creating a task `POST /v1/tasks`. Upon receiving a request, the handler will:
1) Create a new task driver using the controllers `createNewTaskDriver` method
2) Initialize the task
3) Render the template
4) Apply the task if RunOption = "now"
**JSON request:**
```json
{
"description": "Writes the service name, id, and IP address to a file",
"enabled": true,
"name": …
```
=> Feature 522 create task handler endpoint

e2e/command_tls_test.go
Some e2e tests were checking for the Terraform output "Your infrastructure
matches the configuration". However, looks like this output has been reworded to
"Infrastructure is up-to-date".
Update test to check for output that is set by CTS
Example:
```
command_tls_test.go:621: 
Error Trace:	command_tls_test.go:621
Error:      	"==> Inspecting changes to resource(s) if enabling 'e2e_task_api_db'...\n\n    Generating plan that Consul Terraform Sync will use Terraform to execute\n\n    Refreshing Terraform state in-memory prior to plan...\nThe refreshed state will be used to calculate this plan, but will not be\npersisted to local or remote state storage.\n\nmodule.e2e_task_api_db.local_file.address[\"db.node-7dd7f521-b137-7bf8-6548-1060a432b75b.dc1\"]: Refreshing state... …
```
=> Update e2e tests checking for Terraform output that changed

api/representation_test.go, config/condition_services.go, config/condition_services_test.go, config/condition_test.go, config/monitor_services.go, config/monitor_services_test.go, config/source_input_services.go, config/source_input_services_test.go, config/source_input_test.go, config/task.go, config/task_test.go
Add new `names` config. Examples:
```
source_input "services" {
names = ["api", "web"]
}
```
```
condition "services" {
names = ["db"]
}
```
Changes:
- Add support regexp="" as a valid regex (needed to determine if regexp is configured or not)
- Add names field
- Update `condition "services"` and `source_input "services"` relationship with `task.services` list such that condition nor source_input can be configured when services list is configured
- This is backwards breaking but in a non-meaningful way
- Users were previously not permitted to configure condition/source_input services with a regexp along with task.services
- With this change, users can no longer configure an empty condition/source_input services
```
task {
name = "task"
description = "example of empty cond with services - …
```
=> Add `names` config field to `condition "services"` and `source_input "services"`

.github/workflows/build.yml, .release/ci.hcl, .release/security-scan.hcl, Dockerfile
What this PR does is it enables security scanning (owned by the Security team) for this repository. This is a part of the Common Release Tooling (CRT) effort which `enables a consistent workflow for security scanning that can be used across products and services. It provides a single abstraction point to allow us integrate our own scanning capabilities, as well as leverage external tools and APIs from vendors, open source, or free-to-use projects.` Learn more about HashiCorp's security-scanner [here](https://github.com/hashicorp/security-scanner/).
While running the security scan tests, I ran into several [false positives](https://github.com/hashicorp/crt-workflows-common/runs/4472723819?check_suite_focus=true) with `secrets` in the …
=> Enable Security Scanning (CRT)

api/api.go, api/middleware.go, api/response_writers.go, e2e/api_test.go
This PR adds new middleware for REST request handling. 
1) refactor the swagger middleware 
2) new response writer and middleware for handling atypical/non-json error responses.
3) new response writer for getting the status code so it can be logged
**Error Plaintext**
The swagger 3rd party middleware writes out a plaintext error response if validation fails:
`request body has an error: doesn't match the schema: Error at "/enabled": Field must be set to boolean or not be present`
With the new response writer, this plaintext response is caught and re-processed into the correct CTS JSON error response:
```json
{
"error": {
"message": "request body has an error: doesn't match the schema: Error at \"/enabled\": Field must be set to boolean or not be present\n"
},
"request_id": …
```
=> added response writers and middleware

config/monitor_services.go, templates/tftmpl/template.go, templates/tftmpl/template_catalog_services.go, templates/tftmpl/template_consul_kv.go, templates/tftmpl/template_services_regex.go, templates/tftmpl/tfvars.go, templates/tftmpl/variables.go
PR of a few fixes in the templating code resulting from starting to support `names` for condition "services"
Related PRs:
- https://github.com/hashicorp/consul-terraform-sync/pull/543
- https://github.com/hashicorp/consul-terraform-sync/pull/544
Each commit is self-contained
=> Templating cleanup and fixes

config/monitor_services.go, config/monitor_services_test.go
Check that services names in `names` field are not empty strings
=> Add condition/source_input "services" names field empty string validation

templates/tftmpl/template_services_regex.go, templates/tftmpl/template_services_regex_test.go, templates/tftmpl/tmplfunc/services_regex_test.go
Previously updated condition/source_input "services" regexp configuration to
support an empty string (which is behaves the same as a wildcard)
Commit: https://github.com/hashicorp/consul-terraform-sync/pull/543/commits/89785a332c572fc24c248927cd978814226e7175
Update templating, which did a check for `regexp == ""`, to allow template and hcat
query to be appended
=> Support condition/source_input "services" regexp empty string

api/task.go, api/task_create.go, api/task_create_test.go, e2e/api_test.go
Previously, we were always creating an event. If the task was not created in the end,
we would then have an oprhaned event that had no driver associated with it. This caused
an error when getting the overall event statuses.
For a task that is created and not run, the status will be unknown until the first run
is triggered.
Changes:
- Moved where we call the task apply out of the initNewTask method and into the main creation method
- Update storing event to only happen if the task was applied successfully with `?run=now`
- Moved the initialization to happen before checking whether `?run=inspect`
=> Only store events on task creation if the task ran successfully

command/meta.go, command/task_delete.go, command/task_disable.go, command/task_enable.go, e2e/command_test.go
Adds `-auto-approve` as an option to skip the interactive approval step when enabling a task that has changes or deleting a task. The flag name was based on [a similar option for Terraform apply](https://www.terraform.io/cli/commands/apply#automatic-plan-mode).
For enabling tasks, if there are changes, CTS will still inspect the task and output the Terraform plan so that users are able to see what changes will happen when the apply is run.
This same option will be added to task creation once the CLI command has been implemented.
=> Auto-approve option for delete and enable commands

e2e/compatibility/consul_test.go, e2e/e2e_test.go, go.mod, go.sum, templates/hcltmpl/dynamic.go, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/services_regex.go, templates/tftmpl/tmplfunc/tmpl_func.go
The fix for https://github.com/hashicorp/consul-terraform-sync/issues/430 was a breaking change intended for 0.5.0 to change the default monitoring to be only passing services (rather than all services regardless of status).
Original PRs:
- https://github.com/hashicorp/consul-terraform-sync/pull/450
- https://github.com/hashicorp/consul-terraform-sync/pull/455
It was reverted due to a different branching strategy for 0.4.1. Reverted changes:
- https://github.com/hashicorp/consul-terraform-sync/pull/463
- https://github.com/hashicorp/consul-terraform-sync/pull/462
This PR undoes the reverts above:
- Adds back e2e test for expected behavior (test initially fails)
- Update hcat with latest on master, which contains the fix https://github.com/hashicorp/hcat/pull/72
- Includes a few other …
=> Undo revert of default to monitoring only passing services

.github/workflows/build.yml, .release/ci.hcl, .release/security-scan.hcl
Right before the holiday, I added `security-scanner` a tool built by Security in this repository for Common Release Tooling. However, there was an issue in the security-scanner that was fixed just until recently. View the change log [here.](https://github.com/hashicorp/security-scanner/releases/tag/v0.0.1-alpha7) This PR is an update to change `secrets` from `false` to `true` to enable security-scanning for secrets in both of the `binaries` and `containers` stanzas in the `security-scan.hcl` file.
More information about what the issue was can be found in this merged [PR #545](https://github.com/hashicorp/consul-terraform-sync/pull/545)
The tests are now passing! :yay-frog:  
[security-scan-binaries](https://github.com/hashicorp/crt-workflows-common/actions/runs/1659884998) …
=> Fix + Update Security Scanner for CRT

api/server.go, api/task_create.go, api/task_create_test.go, controller/server.go, e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, mocks/server/server.go
This is needed in CTS enterprise to return the run URL of the TFC speculative plan. Also fixed the benchmark tests which were still expecting the Controller interface instead of a ReadWriteController.
=> Update TaskInspect to return an additional string

api/task_create.go, controller/server.go, driver/terraform.go
The Terraform driver currently will not return anything for the URL,
but this will allow the Terraform Cloud driver to return a URL.
=> Add option to return a URL as part of inspection

api/test.go, controller/readonly.go, e2e/e2e_test.go
Inspect mode was not printing the plan results because we started
returning the plan to the inspect API. Moved the logging to the
controller so that it is only printed in inspect mode.
**Before**
```
2022-01-07T13:23:39.720-0600 [INFO]  ctrl: inspecting all tasks
2022-01-07T13:23:39.831-0600 [INFO]  ctrl: inspecting task: task_name=test-task
2022/01/07 13:23:39 [INFO] running Terraform command: /.../terraform plan -no-color -input=false -detailed-exitcode -lock-timeout=0s -var-file=terraform.tfvars -var-file=providers.tfvars -lock=true -parallelism=10 -refresh=true
module.test-task.local_file.greeting_services: Refreshing state... [id=f1f13de367505e14bf6928dd14534de0788ff510]
module.test-task.local_file.greeting: Refreshing state... [id=69342c5c39e5ae5f0077aecc32c0f81811fb8193]
No …
```
=> Fix logging Terraform plan output in inspect mode

config/monitor_services.go, config/monitor_services_test.go, driver/task.go
Make an exception to allow `regexp` config field for ServicesMonitor to remain
nil even after Finalize() and Validate()
Reason: we may want to validate a config multiple times
Source: https://github.com/hashicorp/consul-terraform-sync/pull/587#discussion_r779917409
=> Keep `regexp` nil when unset for ServicesMonitor config

api/representation.go, api/representation_test.go, api/response_writers.go, api/task_create.go, api/task_create_test.go, api/task_lifecycle_client.go, command/commands.go, command/meta.go, command/task_create.go, e2e/command_test.go
This PR is for a new CLI client for creating a new task
- create task command allows a user to create a new task using a provided `.hcl` file containing a single task (and only a single task)
- currently doesn't support adding terraform variables or terraform variable files, this will need to be added in a future PR
- the CLI output for `create task` is a WIP, this is the first pass. One area that could be improved (possible in a future PR) is replacing the current JSON task output with a customized human readable output as discussed with @findkim 
- CLI output when connecting to a server with the wrong scheme is not displaying the correct message. This is a known issue and is being tracked. This issue only effects the CLI output, TLS/mTLS is functionally working as intended. …
=> Feature 522 create client cli

api/api.go, api/api_test.go, api/overall_status.go, api/overall_status_test.go, api/server.go, api/server_test.go, api/task_status.go, api/task_status_test.go, command/cli.go, controller/server.go, mocks/server/server.go
Last series of the API refactor PRs for now to increase data encapsulation of the server implementation.
* Replaces store/driver dependencies in the API handler for `/v1/status`, `/v1/status/tasks`, and `/v1/status/task/:task_name`
* Reduce tests sleeping 3s each waiting on starting up go server
Note for the future: the server interface in the `api` package is growing, it may get to the point we need to break up the interfaces and group them by domain. We'll see how this shakes out.
```go
type Server interface {
Config() config.Config
Events(ctx context.Context, taskName string) (map[string][]event.Event, error)
Task(ctx context.Context, taskName string) (config.TaskConfig, error)
TaskCreate(context.Context, config.TaskConfig) (config.TaskConfig, error)
TaskCreateAndRun(context.Context, …
```
=> Refactor api status endpoints to use server interface

api/representation.go, api/representation_test.go, command/task_create.go, controller/server.go, controller/server_test.go, driver/task.go, e2e/command_test.go, e2e/test_modules/with_tfvars_file/main.tf, e2e/test_modules/with_tfvars_file/variables.tf, templates/tftmpl/module_variables.go
This PR covers the following enhancements and fixes:
1) configFromDriverTask would panic when a variable was provided that was not of type string:
https://github.com/hashicorp/consul-terraform-sync/blob/fe685da4621d396c46fa44fea27db0aca35f1573/controller/server.go#L172-L175
This was because the value could be of any type, not just a string. If a non string type is used with `.AsString()` this function will panic.
2) Create task CLI should handle the conversion of terraform variable files included in a task definition into 
map[string]string for remote requests.
**Example Task with Terraform varfiles:**
``` hcl
task {
name           = "api-task"
description    = "Writes the service name, id, and IP address to a file"
module         = "./variables-module"
providers      = ["local"]
services …
```
=> Feature 522 add terraform variable file create task cli

controller/controller_test.go, controller/readonly_test.go, controller/readwrite.go, controller/readwrite_test.go, controller/server_test.go, driver/driver.go, driver/drivers.go, driver/terraform.go, driver/terraform_test.go, go.mod, go.sum, mocks/driver/driver.go, mocks/templates/watcher.go, templates/hcat.go, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/services_regex.go
hcat would update the query index for blocking queries as expected since https://github.com/hashicorp/hcat/pull/73, but CTS was not utilizing it in the next API request to Consul and instead using a clean `hcat.QueryOptions` that didn't have reference of the iterating index.
Changes now use the updated query options by using it as the base and merging in the other query parameters. This was my bad missing this detail when I had attempted to fix it earlier https://github.com/hashicorp/consul-terraform-sync/pull/460
Resolves https://github.com/hashicorp/consul-terraform-sync/issues/529
Fixing the blocking query exposed an existing race condition whether the API request for the health service or catalog-services would return within a …
=> Fix query types to use blocking queries

config/condition_schedule.go, config/module_input.go, config/module_input_test.go, config/monitor.go, config/monitor_catalog_services.go, config/monitor_consul_kv.go, config/monitor_no.go, config/monitor_services.go
This is the first PR out of ~3 PRs for [Expand usage of module_input / source_input block](https://github.com/hashicorp/consul-terraform-sync/issues/607)
Change: add new configuration type `ModuleInputConfigs` in order to allow multiple configuration per task
Subsequent change: update TaskConfig to replace ModuleInputConfig with ModuleInputConfigs (note plural).
=> Add new configuration type ModuleInputConfigs

api/api_test.go, e2e/condition_schedule_test.go
https://github.com/hashicorp/consul-terraform-sync/pull/535 added 1 second delay to Catalog Services condition and services condition with regex
=> Bump tests with timing for catalog-services or services+regexp delay

driver/terraform.go, driver/terraform_test.go, e2e/condition_schedule_test.go, e2e/module_input_test.go, templates/tftmpl/notifier/catalog_services_registration.go, templates/tftmpl/notifier/catalog_services_registration_test.go, templates/tftmpl/notifier/consul_kv.go, templates/tftmpl/notifier/consul_kv_test.go, templates/tftmpl/notifier/services.go, templates/tftmpl/notifier/services_test.go, templates/tftmpl/notifier/suppress_notification.go
"Final" PR for [Expand usage of module_input / source_input block](https://github.com/hashicorp/consul-terraform-sync/issues/607)
Earlier PRs:
1. Added ModuleInputConfigs object. Updated config validation for supporting multiple module_input blocks ([link](https://github.com/hashicorp/consul-terraform-sync/pull/608))
2. Update TaskConfig with ModuleInputConfigs. Updated config validation for impact on conditions. Includes downstream changes to driver, controller, etc. ([link](https://github.com/hashicorp/consul-terraform-sync/pull/610))
This PR: update notifiers to handle module inputs to other types of conditions (previously only schedule condition)
- Add a Services notifier for services condition and services list to suppress module inputs
- Update other notifiers to support …
=> Update Notifiers to support Module Inputs with Other Condition Types

controller/readwrite.go, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/services_regex.go
Context: `TestCondition_Schedule_Basic/module_input_services` (services regex
module_input) was flaking because when two monitored services are registered
simultaneously, the servicesRegexQuery.Fetch() would only return one of the
monitored services because the second services hadn't propagated through Consul
yet.
Previously tasks were all triggered when any dependency was updated. This likely
created a natural delay for service propagation. Recent refactors to trigger
individual tasks only when their dependency updates, removed that delay and
exposed this race condition and increased test flakiness.
Worked on together with @findkim
=> Move service propagation wait time into tmplfunc Fetch

api/api_test.go, controller/readwrite.go, controller/server.go, e2e/api_test.go, event/event.go, event/event_test.go
Closes: https://github.com/hashicorp/consul-terraform-sync/issues/569
This is part of the work to rename 'source' to 'module'. This PR adds the new 'module' field but leaves the 'source' field as is for now. Later at an announced time, 'source' field will be removed.
Future work: renaming driver for various 'source' language.
Note: I kept the 'source' variable name the same i.e. `Config.Source` rather than following other deprecation patterns to rename the field to `Config.DeprecatedSource`. My thought was that it might be potentially a breaking change since users might use the `Config{}` to unmarshall JSON? Feedback appreciated. Thank you
=> Deprecate events payload 'source' field for new 'module' field

command/meta.go, e2e/command_test.go
**Description**
The option `-http-addr` was added to the CLI as part of implementing TLS on the CTS API (https://github.com/hashicorp/consul-terraform-sync/pull/490). This allows users to specify the whole address of the CTS API, including the port, so `-port` should be deprecated in favor of `-http-addr`.
---
Added 'deprecated' to the helper text of 'port' flag.
Switched usage of 'port' to 'http-addr' in e2e tests.
Output after the change:
```
$ $GOPATH/bin/consul-terraform-sync task disable -port=8558 example-task
==> Waiting to disable 'example-task'...
Warning: 'port' option is deprecated and will be removed in a later version. It is preferred to use the 'http-addr' option instead.
==> 'example-task' disable complete!
```
=> Deprecate `port` CLI option

e2e/test_modules/delayed_module/variables.tf
When run locally (on a Mac, bash shell), the `sleep 5s` command in the TF module does not run, only `sleep <value>` is supported. Since the default for the sleep command is seconds, the `s` is being removed.
Reference [1]:
```
Please note that the sleep command in BSD family of operating systems (such as FreeBSD) or macOS/mac OS X does NOT take any suffix arguments (m/h/d). It only takes arguments in seconds. So syntax for sleep command for Unix like system is:
sleep NUMBER
```
[1] https://www.cyberciti.biz/faq/linux-unix-sleep-bash-scripting/
=> Fix E2E test - TF module sleep usage

driver/terraform.go, driver/terraform_test.go, e2e/api_test.go, e2e/command_test.go
Removed the restriction where only enabled tasks were initialized. This solves a bug that occurs only in the case where a task is initially disabled and then enabled for the first time, which was introduced during a previous refactor. It also has the advantage of catching initialization errors earlier at start up or creation instead of when it is first enabled.
**Bug Details:**
After enabling a task that was initially disabled (setting `enabled=false` in either the config file or in a create task API request), the task was not executing when there were changes in Consul and logging `template was notified for update but the template ID does not match any task`.
The cause of this is that hcat is returning template IDs to the controller and the controller then uses a mapping of the template …
=> Initialize disabled tasks

controller/server_test.go, driver/driver.go, driver/drivers.go, driver/drivers_test.go, driver/terraform.go, driver/terraform_test.go, e2e/command_test.go, e2e/config.go, go.mod, go.sum, mocks/driver/driver.go, mocks/templates/watcher.go, templates/hcat.go
Once a task is created via the CLI, the task doesn't update with latest var.services on Consul catalog changes.
I noticed that when a task is created with inspect, and when a task is deleted, service changes still trigger the watcher. I see the following log:
```
2022-01-18T15:14:04.169-0800 [DEBUG] ctrl: template was notified for update but the template ID does not match any task: template_id=389697c5d1a1b87d1b059e80c7c08103
```
I added Deregister functionality to hcat, and added a public method. Now inspect and delete calls will call the deregister function, which fixes the issue.
part of #522
=> Feature 522 fix watcher after delete and inspect

controller/readwrite.go, controller/readwrite_test.go, controller/server.go, e2e/condition_schedule_test.go
This fixes the problems of scheduled tasks created with the API were not running and scheduled tasks deleted with the API were not stopped.
Added a channel to coordinate with the controller's `Run()` function, which indicates that there is a new scheduled task that needs to be started. For deletion, I went with exiting the go routine if the task was no longer still in the map of drivers. The scheduled task essentially won't be stopped until the next run after deletion. I'm open to other ideas on how to handle this, though!
Example:
Note the difference between the API request and when the stopping deletion is logged.
```
2022-01-24T17:27:45.005-0600 [INFO]  ctrl: time for scheduled task: task_name=scheduled-task
2022-01-24T17:27:45.005-0600 [INFO]  ctrl: scheduled task triggered but had no …
```
=> Fix scheduled tasks created and deleted via the API

.github/workflows/build.yml
This corrects a longstanding issue with DNS on mac builds that we were unable to address until migrating our build platform.
=> add netcgo tag to darwin build

command/task_create.go
Outputting the URL to the TFC speculative plan if returned by the API.
TFC Inspect:
```
==> Inspecting changes to resource if creating task 'mkam_test_task'...
Generating plan that Consul Terraform Sync will use Terraform to execute
Request ID: d23a047c-771b-c25c-5393-3b7c92c419c7
Task: {
"condition": {
"services": {
"names": [
"api",
"web"
],
"use_as_module_input": true
}
},
"module": "mkam/hello/cts",
"name": "mkam_test_task"
}
Plan:
Terraform v1.1.4
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
{"@level":"info","@message":"Terraform 1.1.4","@module":"terraform.ui","@timestamp":"2022-01-27T21:58:55.218688Z","terraform":"1.1.4","type":"version","ui":"1.0"}
...
{"@level":"warn","@message":"Warning: Value for undeclared …
```
=> Output TFC run URL in approval prompt

e2e/api_test.go, e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/condition_service_test.go, e2e/config.go, e2e/e2e_test.go, e2e/utils.go
Context:
- "SourceIncludesVar" deprecated - results in some of the "include" wording losing context: [#568](https://github.com/hashicorp/consul-terraform-sync/issues/568)
- "Source" wording to refer to Terraform module is deprecated: [#566](https://github.com/hashicorp/consul-terraform-sync/issues/566), [#567](https://github.com/hashicorp/consul-terraform-sync/issues/567)
This PR removes this deprecated language from the the e2e directory
Future work:
- Rename deprecated language in remaining directories
=> Rename "source" and "include" related wording in e2e directory

api/task_create.go, controller/server.go, controller/server_test.go, driver/terraform.go, go.mod, go.sum
This PR adds the SetBufferPeriod function back into the Create Task CLI/API flow. This was removed because a bug in hcat was causing this not to work as expected. WIth the latest hcat this has been resolved.
A buffer period is defined as
``` json
"buffer_period": {
"enabled": true,
"min": "10s",
"max": "60s"
}
```
I manually tested the `min` was being honoured using the following scenarios and verified it worked as expected:
1) Created a task without a task buffer_period, confirmed it used the CTS configuration as default
- Confirmed it works with a disabled buffer_period configured in CTS
- Confirmed it works with an enabled buffer_period configured in CTS
2) Created a task with a task buffer_period, confirmed it used the tasks buffer period
- confirmed it works with a disabled …
=> Feature 522 set bufferperiod

api/representation.go, config/condition.go, config/condition_no.go, config/monitor_no.go, config/task.go, config/task_test.go, examples/reference-example/example-config.hcl, examples/reference-example/sync-tasks/my-task/main.tf, examples/runnable-example/config.hcl, examples/runnable-example/example-module/README.md
Previously, deprecated configurations regarding "source", "src", "included" were
updated in the templates, driver, and e2e directory.
This is the final search across the whole CTS repo for this language
Commits:
- Rename "source", "src", and "include"
- Rename NoMonitorConfig => NoConditionConfig to adjust for change to support multiple `module_input` blocks
=> Final updates for "source", "src", and "include"

CHANGELOG.md
This changelog update reflects the change to how the minimum value of the buffer period is used when triggering a task.
=> Update changelog with buffer period min behavior change

.github/workflows/build.yml
My sincere apologies for leaving this line here -- I did not realize it was used for testing purposes for the RDX team. 
This is part of the effort to maintain the build.yml files neat and up to date with the current CRT convention. 
More information can be found in PR #656 on why this line is removed.
=> removing workflow dispatch as it is not needed (for release/0.2.x)

.github/workflows/build.yml
My sincere apologies for leaving this line here -- I did not realize it was used for testing purposes for the RDX team. 
This is part of the effort to maintain the build.yml files neat and up to date with the current CRT convention. 
More information can be found in PR #656 on why this line is removed.
=> removing workflow dispatch as it is not needed (for release/0.3.x) 

.github/workflows/build.yml, .release/ci.hcl
What this PR does is it updates the `build.yml` to the `main` branch to make the workflow a bit more drier and matches the current convention that's in [crt-core-helloworld.](https://github.com/hashicorp/crt-core-helloworld/blob/main/.github/workflows/build.yml)
This updates the build to follow a matrix approach, cleans up the linux-packaging, and making the workflow more abstract and easier to read. 
If there are any questions or if anything is not clear, please feel free to ask! ❤️  
Test are passing [here.](https://github.com/hashicorp/crt-workflows-common/actions/runs/1780380484)
=> [RDX-272] Update build.yml 

.github/workflows/build.yml, .release/ci.hcl, .release/security-scan.hcl
What this PR does is it updates the `build.yml` to the `release/0.4.x` branch to make the workflow a bit more drier and matches the current convention that's in [crt-core-helloworld.](https://github.com/hashicorp/crt-core-helloworld/blob/main/.github/workflows/build.yml)
This updates the build to follow a matrix approach, cleans up the linux-packaging, and making the workflow more abstract and easier to read. 
I also noticed that this branch did not have `security-scanner`, that was added as well :) 
If there are any questions or if anything is not clear, please feel free to ask! ❤️  
Test are passing [here.](https://github.com/hashicorp/crt-workflows-common/actions/runs/1780547448)
=> [RDX-272] Enable security-scan and update build.yml for release/0.4.x branch

api/api.go
When initially taking on this task, I was going to increase the timeout to some average large value, however after some investigation I decided to instead remove the timeout alltogether.
It was expected that setting the writeTimeout would cause a connection to terminate upon timeout expiration, however, this is not the case. What actually happens is that the underlying connection is closed, but, the server doesn't return an error until the connection is accessed again (i.e. when calling a ResponseWriter()).
WriteTimeout = 15 seconds
User makes an API call to Create Task
Server receives request and creates the task, it takes 40 seconds to complete, then the ResponseWriter is called
A timeout occurred, so the client receives an error, but not until ResponseWriter is called
So the client …
=> Removed `http.Server` write timeout, will now not timeout

config/condition.go, config/condition_consul_kv.go, config/condition_services.go, config/config.go, config/monitor_catalog_services.go, config/task.go
Update: the link to consul.io docs in the example outputs are still only in staging. Here's an example consul.io link: https://consul-2poy7q5me-hashicorp.vercel.app/docs/nia/release-notes/0-5-0
source_includes_var example:
```
2022-02-03T18:23:15.205-0500 [WARN]  config.task: the 'source_includes_var' field in the task's consul-kv condition block is deprecated in v0.5.0 and will be removed in v0.8.0.
Please replace 'source_includes_var' with 'use_as_module_input' in your condition configuration.
We will be releasing a tool to help upgrade your configuration for this deprecation.
Example upgrade:
|    task {
|      condition "consul-kv" {
|  -     source_includes_var = false
|  +     use_as_module_input = false
|      }
|      ...
|    }
For more details and examples, please see: …
```
=> Update deprecation warning logs for config streamlining

api/task_lifecycle_client.go, command/cli.go, command/commands.go, command/meta.go, command/task_create.go, command/task_delete.go, command/task_enable.go, e2e/command_test.go, e2e/command_tls_test.go, logging/logging.go
This PR attempts to improve the UX for the `task create` CLI in a number of ways:
1. Make error "categories" and group like errors closer together in code, subsequent statements provided more details about the error. For example a group of errors related to `Error: unable to create request`
2. Make constants for common CLI error types like `Error: unable to create request` or `Error: unable to create client`
3. Make it clearer that the JSON that is returned during the `inspect` phase of the create is the `Request Payload`
4. Add `no or blank` to the accept/reject instructions to provide the user with confidence when rejecting a plan
5. Disabled logging when running the CLI. We want to control the output completely, so we don't want other parts of the code logging to the output
- These are …
=> Updates to cli ux

.circleci/config.yml, Makefile, e2e/benchmarks/benchmarks_test.go, e2e/compatibility/consul_test.go, templates/hcltmpl/vault_test.go
Some of our weekly tests have separate build tags.
This makes it easy to accidentally make a change so that they cannot compile
without noticing. Because these tests also run weekly, the issue may not be
discovered as late as a week later.
This change adds a compile check to be run in circleci when a branch is pushed
or on a merge to main.
=> Add basic compile test for weekly tests to CI

api/task_create.go, controller/readwrite.go, driver/terraform.go, driver/terraform_test.go, e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/condition_service_test.go, e2e/e2e_test.go, e2e/module_input_test.go, go.mod, go.sum, mocks/templates/watcher.go, templates/hcat.go, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/catalog_services_registration_test.go
Added a validation step after the template has been registered that executes the fetch request on all the Consul dependencies. This is intended to catch issues like invalid query parameters (setting a datacenter that does not exist, using the Consul enterprise namespace feature against an OSS Consul instance, etc.). By failing faster on invalid query parameters, it also fixes a bug in the create API workflow, as described below.
**Example Output**
```
consul-terraform-sync task create -task-file=task.hcl
==> Inspecting changes to resource if creating task 'mkam_test_task'...
Generating plan that Consul Terraform Sync will use Terraform to execute
==> Error: unable to generate plan for 'mkam_test_task'
request returned 400 status code with error: unable to retrieve data from
Consul: …
```
=> Validate template dependency queries at task initialization

config/config.go
'service' block deprecation message was incorrectly being logged when config.Services is not nil but an empty array.
Also renamed message const name to match other deprecation messages
Thanks @mkam for finding this!
=> Fix issue: 'service' block deprecation is logged even when not configured

config/condition_test.go, config/config_test.go, config/module_input_test.go, config/testdata/merge/taskA.hcl, config/testdata/merge/taskB.hcl, e2e/api_test.go, e2e/compatibility/consul_test.go, e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/condition_schedule_test.go, e2e/config.go, e2e/e2e_test.go, e2e/tasks_test.go, examples/reference-example/example-config.hcl, examples/runnable-example/README.md, examples/runnable-example/config.hcl, examples/runnable-example/example-module/README.md, examples/runnable-example/example-module/main.tf
Upgrades our config snippets containing the deprecated `services` field and `service` block with the replacement or removes it completely.
Adds a placeholder e2e test to specifically test all config streamlining related deprecations
=> Deprecate 'services' field and 'service' block in config snippets

driver/terraform.go, e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/condition_service_test.go, e2e/e2e_test.go, e2e/module_input_test.go
Some follow up improvements to the validate template changes (https://github.com/hashicorp/consul-terraform-sync/pull/662) that I realized after this merged.
- Changed to using our interface for hcat template instead of hcat.Template directly
- Renamed `testInvalidQueries` to `testInvalidTaskConfig` because this test can be used for any invalid config that fails to create, not just for invalid queries
=> Improve validate template signature and test names

api/oapigen/client.go, api/oapigen/server.go, api/openapi.yaml, api/task.go, api/task_create_test.go, api/task_delete.go, api/task_delete_test.go, api/task_get.go, api/task_get_test.go, e2e/api_test.go
Add support for a Get Task API.
Note: this API will be used to replace the task configuration information that is deprecated in the Task Status API
Example:
`curl localhost:8558/v1/tasks/kv_task`
```
{
"request_id": "4859e3ad-125a-bd71-ac63-0ac883a810bf",
"task": {
"buffer_period": {
"enabled": true,
"max": "20s",
"min": "5s"
},
"condition": {
"consul_kv": {
"datacenter": "",
"namespace": "",
"path": "my_key",
"recurse": false,
"use_as_module_input": true
}
},
"description": "",
"enabled": true,
"module": "/Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/build/modules/consul_kv_file",
"module_input": {
"services": {
"cts_user_defined_meta": {},
"datacenter": "",
"filter": "",
"names": [
"api"
],
"namespace": ""
}
},
"name": "kv_task",
"providers": [],
"services": [], …
```
=> Get Task API

api/api_test.go, api/task_status.go, controller/readwrite.go, controller/server.go, e2e/api_test.go, event/event.go, event/event_test.go
In a previous PR I deprecated `Events.Config.Source` and introduced `Events.Config.Module` as a replacement in the Task Status API response: https://github.com/hashicorp/consul-terraform-sync/pull/618
Instead, we want to deprecate `Events.Config` and additional task-config related fields from the Task Status API response. This is because they are not status information.
This information is better suited for a Get Task API, which we will introduce to replace the response deprecations.
Changes (details in commit)
- Manually revert https://github.com/hashicorp/consul-terraform-sync/pull/618
- Add deprecation comments
=> Update Task Status API response deprecations

controller/readwrite.go, controller/server.go, controller/server_test.go, driver/drivers.go, e2e/command_test.go
This PR fixes an issue where the attempted creation of a bad task, for example, one with a non existent module, would lead to the inability to then re-create or delete the task.
The cause of this was that because the validity of the module path was not checked until after the driver was created, the driver was not appropriately cleaned up before returning the error leading to a dangling watcher. This task adds cleanup steps if a task driver is successfully created, but then it errors later in the creation process
part of #522
=> Create task module no exist error

driver/terraform.go, templates/hcat.go
After I had changed to using our template interface instead of directly using a hcat template for template validation (https://github.com/hashicorp/consul-terraform-sync/pull/677), I realized that our custom notifiers that implement the template interface won't mark the template as dirty with `Notify(nil)`. I considered modifying the custom notifiers, but decided to revert this back to expecting `*hcat.Template` for more predictable behavior.
Made some additional improvements that I thought of as I was debugging an issue related to this change:
- Added some debug logs around the template validation
- Moved validation before registration so that we don't have to deregister on error
- Changed the variable names of the errors in ValidateTemplate for improved clarity
=> Revert back to validating template with hcat templates

api/representation.go, api/representation_test.go
Context:
- Create Task API does not support task creation with `services` field
- As a result, the `services` field is not supported in openapi
- CTS config file still supports task creation with `services` field
The Get Task API needs to support returning `services` field information when
the task has a `services` field. Because the `services` field is not available
to the API, convert the `services` information to a condition / module_input.
=> Handle deprecated 'services' in API representation

command/meta.go, command/task_delete.go, e2e/command_test.go, e2e/condition_schedule_test.go
Add more information on how a task is deleted to the approval prompt and change 'is marked' to 'has been marked', per the very helpful suggestions by @jherschman!
```
$ consul-terraform-sync task delete test-task
==> Do you want to delete 'test-task'?
- This action cannot be undone.
- If the task is not running, it will be deleted immediately.
- If the task is running, it will be deleted once it has completed.
Only 'yes' will be accepted to approve, enter 'no' or leave blank to reject.
Enter a value: yes
==> Marking task 'test-task' for deletion...
==> Task 'test-task' has been marked for deletion and will be deleted when not running.
```
=> Update delete command output

command/task_create.go
- user is informed that task is being created and being run.
- user is informed that this can take some time
- user is informed that terminating the task will not result in stopping task creation
Example
```
$consul-terraform-sync task create -task-file=task.hcl
// redacted for brevity
==> Creating and running task api-task...
The task creation request has been sent to the CTS server.
Please be patient as it may take some time to see a confirmation that this task has completed.
Warning: Terminating this process will not stop task creation.
==> Task 'api-task' created
Request ID: '86bb3e0b-3548-5e02-3337-466c4d03e6ff'
```
=> Improved messaging when creating a task

config/config.go, config/config_test.go, controller/controller.go, controller/readwrite_test.go
Mark service blocks config as deprecated to discourage further usage in code until removal. Also served as an easy way to audit usage of service block config field in tests.
- Rename `Services` with `DeprecatedServices`
- Remove unnecessary test references to `Services`
=> Replace CTS config Services blocks to DeprecatedServices in backend

api/representation.go, api/representation_test.go
When a task is created through Create Task API with a catalog-service condition
and no node_meta configured, node_meta is nil and leads to a panic.
Ex create task api request
```
{
"task": {
"condition": {
"catalog_services": {
"regexp": "api"
}
},
"name": "ls_api_cs_2",
"module": "lornasong/cts_file/local",
"version": "0.0.1"
}
}
```
Changes:
- test-case for when node meta is nil (should fail)
- handle node meta nil
Note: API representation was added within this same release
=> Handle when CatalogService condition NodeMeta is nil in representation

api/representation.go, api/representation_test.go, e2e/api_test.go, e2e/e2e_test.go
When starting up CTS with a task that has `services` field configured as the condition (i.e. no condition block is configured), then the services information should be returned in Get Task API as a `condition "services"` with the `names` field assigned to the services information.
Currently, Get Task API is returning this information in the `module_input` block instead of `condition`. 
Changes:
- Add tests to catch this (fails in circleci: [unit/integration](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/3341/workflows/4df7d191-cd9b-493f-b522-dee7e7bfa494/jobs/8922) and [e2e](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/3341/workflows/4df7d191-cd9b-493f-b522-dee7e7bfa494/jobs/8921))
- Fix issue by catching nil condition's finalized …
=> Fix issue in Get Task API for services field as condition 

command/meta.go, command/task_delete.go
Made it the second bullet point since I didn't want it overlooked!
```
consul-terraform-sync task delete test-task
==> Do you want to delete 'test-task'?
- This action cannot be undone.
- Deleting a task will not destroy the infrastructure managed by the task.
- If the task is not running, it will be deleted immediately.
- If the task is running, it will be deleted once it has completed.
Only 'yes' will be accepted to approve, enter 'no' or leave blank to reject.
Enter a value: yes
==> Marking task 'test-task' for deletion...
==> Task 'test-task' has been marked for deletion and will be deleted when not running.
```
=> Clarify that infrastructure is not destroyed on task deletion

templates/tftmpl/notifier/catalog_services_registration.go, templates/tftmpl/notifier/consul_kv.go, templates/tftmpl/notifier/notifier.go, templates/tftmpl/notifier/services.go, templates/tftmpl/notifier/suppress_notification.go
This is only needed by catalog-service to get out of hanging. Other conditions
don't need this call.
It also causes schedule condition to unnecessarily called
terraform-apply on the first scheduled run after a new task is created
(via API/CLI) because the task thinks there are changes.
Related to #704
=> Remove unnecessary template.Notify() calls in overrider

testutils/consul.go
Adding a health check after the service is registered triggers an
additional event in tests, which causes intermittent failures.
I found this is the cause for some of our flaking tests where the event count is greater than the expected count. From what I could tell, no test using this method relies on the assumption that a health check is created.
=> Update bulk services function to skip health check

api/middleware.go
These are logged for every API request and can clutter the logs
Use-case: currently Status API is used in Consul health checks, which can cause this message to log every 10s (or other configured interval)
=> Update general API request received/completed logs from INFO to DEBUG

go.mod, go.sum
The TFC lockup was caused because of a code change to HCAT:
```Go
func (t *Template) Notify(interface{}) bool {
select {
case t.dirty <- struct{}{}:
return true
default:
return false
}
}
```
The t.dirty channel is written to when new data comes in, because the data was never being executed ([due to the isActive logic](https://github.com/hashicorp/consul-terraform-sync/blob/main/controller/readwrite.go#L149-L154)). The t.dirty channel was never being drained, and Notify was always returning false. TFC uses the hcat template, and the hcat template requires notify to return true before it will write to the watcher channel. Since we wrap the hcat template in our own notifier for the OSS conditions, which doesn't require Template.Notify to return true, the lock-up didn't occur on OSS.
part of …
=> upgraded hcat

controller/readwrite.go, controller/readwrite_test.go, e2e/e2e_test.go, e2e/utils.go
Fixes issue where a task triggering change that occurs while the task is currently running is ignored (https://github.com/hashicorp/consul-terraform-sync/issues/732). 
Prior to reverting a hcat change (https://github.com/hashicorp/consul-terraform-sync/pull/740), when using the TFC driver, this ignored run led to a bad state where the task will never be triggered by dependency changes.
**Background**
Previously (as in 0.4.3 and earlier), when any change was detected, we would try to [run all dynamic tasks](https://github.com/hashicorp/consul-terraform-sync/blob/v0.4.3/controller/readwrite.go#L79-L93) and [wait for them to complete](https://github.com/hashicorp/consul-terraform-sync/blob/v0.4.3/controller/readwrite.go#L134). If a change happened while a task was running, it would be …
=> Wait for task to be inactive before running

e2e/e2e_test.go, e2e/test_modules/delayed_module/main.tf
The files were being created at the same time as the resource with
the sleep, so the test was detecting a file that it didn't expect
until the event was completed.
Retried it three times in CircleCI and so far no failures!
=> Create instance files only after initial delay

client/terraform_cli.go, client/terraform_cli_test.go
This PR acts to resolve #701 
CTS handles workspaces with non existing states by checking the [error type returned by Terraform CLI](https://github.com/hashicorp/consul-terraform-sync/blob/2efab4125b2fdcad618118c76c801126e2b4444b/client/terraform_cli.go#L115) . It uses a [regex string](https://github.com/hashicorp/consul-terraform-sync/blob/2efab4125b2fdcad618118c76c801126e2b4444b/client/terraform_cli.go#L20) to match on the error, and if it matches, it then recreates the workspace.
With newer versions of Terraform, the error returned has changed so the error string was no longer matching. Adding the new error string, alongside the old one as to not break compatibility, fixes the issue.
In the future, it would be better if instead the terraform error used the tfexec.ErrNoWorkspace error …
=> Handle missing tf state

api/api_test.go
The TLS tests are occasionally failing because the API has not fully
started. Adjusting the wait time to match what we use for TestServe.
A better fix would be to implement polling that ignores non-connection issues, but I wanted a quicker fix for these tests that have been flaking. Ran 3 times in CircleCI without a failure, though these tests didn't fail super often in the first place. Just enough where I noted the pattern.
=> Wait longer for API to start

controller/readwrite.go, controller/readwrite_test.go, controller/server.go
Changed scheduled task deletion flow to stop the scheduled task immediately. This was accomplished by adding a stop channel for each scheduled task.
Previously, we stopped the scheduled task at the next scheduled run of the task. However, if a task with the same name was created between the deletion and the next scheduled run, the scheduled task would continue running. This was because the method checked if the tasks exists by name and continued running because a task with the same name did exist, even though it was not the original task.
Logs with new workflow:
```
2022-03-03T16:50:11.845-0600 [INFO]  ctrl: scheduled task next run time: task_name=scheduled-task wait_time=1m48.154932s next_runtime="2022-03-03 16:52:00 -0600 CST"
2022-03-03T16:50:11.863-0600 [INFO]  api: starting server: …
```
=> Stop scheduled task as soon as task is deleted

config/config_test.go, config/task.go, config/task_test.go, config/terraform_cloud_workspace.go, config/terraform_cloud_workspace_test.go, controller/controller.go, controller/controller_test.go, controller/server.go, controller/server_test.go, driver/task.go, driver/task_test.go
Add an enterprise-only configuration `task.terraform_cloud_workspace` that handles TFC workspace configurations that are specific to the task (rather than to all tasks, which is handled by the [`driver.workspaces` configuration](https://www.consul.io/docs/nia/configuration#workspaces)). The new configuration is needed to support configuring Terraform Cloud agents with the Terraform Cloud driver. The requirements for the configuration are as followed:
1. Only support "remote" and "agent".
2. Allow agent pool to be identified by either the ID or the name. If both are provided, ID takes precedence.
3. At least one agent pool config is required to be configured if the execution mode is "agent".
4. Agent pool configs should not be set if the execution mode is not "agent".
Example:
```
task { …
```
=> Add Terraform Cloud workspace configuration to tasks

controller/readwrite.go, controller/readwrite_test.go
- Refactor out Once() code into onceConsecutive()
- Make Once mode tests table-driven
Note: easier to view without whitespace: https://github.com/hashicorp/consul-terraform-sync/pull/782/files?w=1
=> Refactor once-mode code

state/event/event.go, state/event/event_test.go, state/event_storage.go, state/event_storage_test.go, state/in_memory_store_test.go
Fixed bug in event storage - using wrong type of lock for delete method
Addressed warnings (unhandled errors, conflicting variable and package names, etc.)
Made small improvements to tests
=> Fixed bug in event storage - using wrong type of lock for delete method

config/auth_test.go, config/buffer_period_test.go, config/condition_catalog_services_test.go, config/condition_consul_kv_test.go, config/condition_schedule_test.go, config/condition_services_test.go, config/config.go, config/config_test.go, config/consul_test.go, config/driver_test.go, config/module_input_consul_kv_test.go, config/module_input_services_test.go, config/monitor_catalog_services_test.go, config/monitor_services.go, config/monitor_services_test.go, config/provider_test.go, config/service_test.go, config/syslog_test.go, config/task.go, config/task_test.go, config/terraform_cloud_workspace_test.go, config/terraform_test.go, config/tls_cts_test.go, config/tls_test.go, config/transport_test.go, config/vault_test.go, state/in_memory_store.go, state/in_memory_store_test.go, state/store.go
Previously introduced storing the configuration in the in-memory state store: https://github.com/hashicorp/consul-terraform-sync/pull/785
Problem: the stored and returned config in NewInMemoryStore() and GetConfig() share references to the child fields
Fix: update these to store/return copies of the config
Changes:
- Commits 1-4: fix some issues with configuration Copy() methods for finalized configs
- Commit 5: fix shared references
- Commit 6: cleanup redundant comments
=> Fix in-memory state store config shared references

driver/terraform_download.go
CTS has the following strategy when determining what version of Terraform to download and use:
1. Use the version specified in the Terraform driver block (`driver.version`)
2. Use the latest version of Terraform
3. If determining the latest version of Terraform fails or if the latest version is not compatible with CTS, then use the hardcoded fallback version.
This PR updates the fallback version to a more recent version of Terraform. The plan is to periodically keep this version more up to date.
=> Update fallback Terraform version to 1.1.8

config/decode.go
Log a more helpful message if the enterprise-only `licence` or `license_path` is
configured. This also makes the UX more consistent with our other enterprise-only
configurations.
Previous error:
```
2022-04-14T17:29:10.464-0500 [ERROR] config: failed decoding content from file: file_path=config.hcl
2022-04-14T17:29:10.464-0500 [ERROR] cli: error building configuration: error="'config.hcl' has invalid keys: license"
```
New errors:
```
2022-04-14T17:21:50.422-0500 [ERROR] config: failed decoding content from file: file_path=config.hcl
2022-04-14T17:21:50.422-0500 [ERROR] cli: error building configuration:
error=
| 'config.hcl' has invalid keys: license_path
| 
| 'license_path' is a Consul-Terraform-Sync (CTS) Enterprise configuration.
```
```
2022-04-14T17:23:37.824-0500 [ERROR] config: …
```
=> Improve error message if license configs set

controller/base.go, controller/base_test.go, controller/condition_monitor.go, controller/condition_monitor_test.go, controller/controller_test.go, controller/readonly.go, controller/readwrite.go, controller/readwrite_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go
Currently, baseController is embedded in TasksManager
This is the first PR in a series of changes to split out baseController from TasksManager. baseController logic is mostly around creating and initializing drivers for tasks. Currently the goal is:
- Convert `controller.baseController` to something like `driver.Factory`
- TasksManager will have a `driverFactory` field and call `driverFactory.Make()` for new tasks (naming input welcome)
This PR starts detangling some of the baseController fields:
- Commit 1: pass in watcher to baseController instead of creating it
- Commit 2: pass in state store to baseController instead of creating it
- Commit 3-4: refactor out a baseController.makeDriver (this is the start of the driverFactory.Make)
- Commit 5-6: create a logger for TasksManager …
=> Split out baseController from TasksManager pt1

command/start.go
- logger was initialized before configuration and used throughout startCommand.Run()
- logger needs to be reset after configuration so that it honors the config
Resolves: #789
=> fixed start logs

config/task.go
Warning should only be logged if there are a non-zero number of services in the
deprecated field.
Noticed that this recently started logging even though I don't have the deprecated field set.
Checked with older versions, and previously when Finalize was called, DeprecatedServices was nil when no `services` configuration was set. At some point, it changed to being an empty but initialized list of strings. This new `else if` is the more appropriate behavior either way, so didn't really look into what made this change.
=> Fix deprecated services warning

api/client.go, api/client_test.go, api/server_test.go, e2e/api_test.go, e2e/command_test.go, e2e/compatibility/consul_test.go, e2e/e2e_test.go, e2e/tasks_test.go, e2e/utils.go
Context:
- Currently the API is served once daemon once-mode was complete
- A lot of tests (e2e in particular) rely on API availability to determine daemon once-mode is complete
Goal: decouple serving the API from daemon once-mode. Serve the API before daemon once-mode
This PR removes test reliance on API availability to determine daemon once-mode is complete. Instead determine once-mode completion by examining the status response rather than API availability.
Future work: move when the API is served to be before daemon once-mode
=> Update e2e test WaitForAPI

config/syslog.go
Context: syslog should be automatically enabled if other fields (e.g. facility
or name) values are provided. This is documented in CTS
Issue: syslog enabled field has to be specifically set to true. Otherwise it is
false even though other config fields are provided.
This was caused by the default was set to enabled=false. When CTS builds the
config, the user-provided config is merged with the default config. If the user
left enabled unconfigured, it would merge with the default enabled=false. This
results in enabled being set to false in a way that looks as though the user set
enabled to false.
Related: https://github.com/hashicorp/consul-terraform-sync/issues/812
=> Fix syslog enabled value

api/client.go
The sleep was added to reduce WaitForTestReadiness impact on resources which
was causing frequent timeouts in Consul start up in e2e tests.
This sleep has since caused flakiness in e2e tests with scheduled tasks where
event runs are counted.
Example:
- 0ms: scheduled task starts running once
- 100ms: WaitForTestReadiness polls - not ready for tests
- 200ms: scheduled task run once complete. 1 event added. Ready for tests
- 300ms: scheduled task runs again on schedule (here's the problem!)
- 400ms: scheduled task run completes. 2nd event added.
- 500ms: WaitForTestReadiness polls - ready for tests
- 501ms: test checks that scheduled task should have run one i.e. 1 event. Test fails
The extra run during the Wait sleep is unlikely but 500ms has a couple instances
of flakiness so far. …
=> Tune WaitForTestReadiness sleep to 100ms

client/consul.go, client/consul_test.go, command/start.go, config/config.go, config/config_test.go, config/consul.go, config/consul_test.go, config/self_registration.go, config/self_registration_test.go, config/testdata/long.hcl, config/testdata/long.json, mocks/client/consul_client.go, registration/manager.go, registration/manager_test.go
First part of implementing self-registration, mostly setting the groundwork and not actually doing any registration yet. 
**Overview of changes**
- Adds configuration for self-registration, which includes a top-level `id` config and a `self_registration` config under the existing `consul` config.
- If `id` is not provided, it is automatically generated in the format of `cts-<uuid>`.
-  A `name` configuration was still under discussion when I started this implementation and will be added in a follow up PR.
- Adds service registration and deregistration methods to the Consul client
- These methods are not currently taking advantage of the improved retry logic added in https://github.com/hashicorp/consul-terraform-sync/pull/818
- Adds a service registration manager, which can register a …
=> Self-Registration with Consul: Configurations, Consul client changes, manager

e2e/benchmarks/task_trigger_test.go, e2e/benchmarks/tasks_concurrent_test.go, e2e/benchmarks/tasks_test.go
- Cleans up some controller variable names that were missed during controller renaming
- Stops controllers to reduce benchmark log clutter
=> Updates to benchmark tests

controller/condition_monitor.go
We weren't logging previously, so there was no indicator that a task
has failed and was no longer executing.
New logs for a dynamic task:
```
2022-05-03T11:14:18.296-0500 [INFO]  tasksmanager: executing task: task_name=failing
2022-05-03T11:14:23.269-0500 [WARN]  task: retrying: attempt_number=2 description="ApplyTask failing"
2022-05-03T11:14:23.640-0500 [ERROR] tasksmanager: error applying task: task_name=failing
error=
| could not apply changes for task failing: retry attempt #2 failed 'error tf-apply for 'failing': exit status 1
| 
| Error: open .terraform/modules/failing/foo.txt: no such file or directory
| 
|   with module.failing.data.local_file.foo,
|   on .terraform/modules/failing/main.tf line 6, in data "local_file" "foo":
|    6: data "local_file" "foo" {
| 
| ': retry attempt …
```
=> Log when dynamic task apply errors

api/oapigen/client.go
We were previously always setting the CreateTaskParams in a client method, so this wasn't
an issue then.
=> Account for nil parameters in request

client/consul.go, controller/daemon.go, controller/daemon_test.go, registration/manager.go, registration/manager_test.go
Adds support for CTS to register itself with Consul when running in daemon mode.
- Updates the health check to use `/v1/health` now that has been implemented
- Adds a Start method to the self-registration manager which will register the service and then wait for an initiated shutdown to deregister the service
- Calls Start() in the daemon controller's Run() to start the registration and monitoring.
- Does not error and exit if there are registration issues, relies on the error logging from the self-registration manager.
- Explicitly deregister CTS if once-mode fails
End-to-end tests will be added in a follow up PR after the remaining work is complete (new configurations, improved retry logic).
=> Self-register CTS as a service with Consul in daemon mode

api/api.go, api/api_test.go, api/health.go, api/health_test.go, api/middleware.go, api/server_test.go, controller/daemon.go, logging/logging.go
Remove logging from `GET v1/health` endpoint call. This is required since we expect the health endpoint to get a lot of "hits" and we do not want to flood the logs
Oapi-codegen generated servers take an all or nothing approach to applying middleware to URIs. We can separate middleware application into groups, however, application of middleware to the oapi-codegen handler is done all at once, with no real way to exclude certain URIs from the middleware (i.e. `v1/health`)
https://github.com/hashicorp/consul-terraform-sync/blob/1bcc8ac9c73847da6f0bc256bd73f249fdcafbbd/api/api.go#L116-L129
https://github.com/hashicorp/consul-terraform-sync/blob/1bcc8ac9c73847da6f0bc256bd73f249fdcafbbd/api/oapigen/server.go#L258-L292
I've opted to handle the exclusion in the middleware itself, the logging …
=> Remove logging from health endpoint

controller/condition_monitor.go, controller/condition_monitor_test.go, controller/daemon.go, controller/daemon_test.go, controller/inspect.go, controller/inspect_test.go, controller/once.go, controller/once_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go
First PR of two to refactor monitoring/triggering out of TasksManager. The intent is to keep TasksManager scoped to managing tasks (crud + run). A separate struct (currently named planning to be named ConditionMonitor) will be used to monitor changes and trigger task runs using the TasksManager.
The changes to disentangle monitoring/triggering code out of TasksManager is pretty large. This first PR contains miscellaneous commits that could be separated out without breaking tests and compilation. The bulk of the refactor will be in the next PR.
=> Refactor monitoring/triggering out of TasksManager (pt1)

controller/condition_monitor.go, controller/condition_monitor_test.go, controller/daemon.go, controller/daemon_test.go, controller/inspect.go, controller/inspect_test.go, controller/once.go, controller/once_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go
Refactor monitoring/triggering out of TasksManager. The intent is to keep TasksManager scoped to managing tasks (crud + run). A separate ConditionMonitor struct will be used to monitor changes and trigger task runs using the TasksManager.
Previous PR https://github.com/hashicorp/consul-terraform-sync/pull/831: contained miscellaneous commits that could be separated out without breaking tests and compilation.
Changes: slowly disentangles variables in TasksManager that are used by ConditionMonitor. Approximate overview of changes:
- Setup ConditionMonitor struct
- Move `watcher` from TasksManager to ConditionMonitor
- Move `watcherCh` from TasksManager to ConditionMonitor
- Remove ConditionMonitor dependency on `drivers` field and drivers in general
- Refactor how newly created schedule …
=> Refactor monitoring/triggering out of TasksManager (pt2)

client/consul.go, client/consul_test.go, registration/manager.go, registration/manager_test.go
#Summary
This ticket introduces handling of errors which can be interpreted as resulting from a missing ACL. In most cases this can be determined by checking for a `403` or `access forbidden` response code from the Consul server, however, Consul team has mentioned that the way ACL access is handled can be non standard, so this cannot be depended on across all endpoints.
Both register and deregister require an ACL with a `service:write` policy, testing the following endpoints:
`/v1/agent/service/register`
`/v1/agent/service/deregister/{service-name}`
I have verified that both return a `403` in the instance where an ACL is used without the `service:write` policy.
When a `403` is returned by the clients `Register` and `Deregister` retrying is stopped, and a `MissingConsulACLError` is …
=> Handle Missing ACL Errors in Consul Client

config/config.go, config/config_test.go, config/consul.go, config/consul_test.go, config/default_check.go, config/default_check_test.go, config/self_registration.go, config/self_registration_test.go, config/testdata/long.hcl, config/testdata/long.json, registration/manager.go, registration/manager_test.go
Add support for configuring the service name and the default health check, allowing users to disable the check and to specify an address if `localhost` does not work in their system.
```
self_registration {
service_name = "test-service"
default_check {
enabled = true
address = "http://172.0.1.23:8080"
}
}
```
Note: Still have `self_registration` for now even though there are discussions to change this.
=> Additional self-registration configurations

client/consul.go
After discussion, it makes sense for the warning log in the Consul Client GetLicense to be removed. The caller of this method would handle the error and perform logging accordingly. The context of the error is not lost as it is wrapped in a NonEnterpriseConsulError.
=> removed warn logging from GetLicense, leave it to the caller

registration/manager.go
Added a warning log to indicate that CTS will continue even if there is an error registering CTS with Consul
=> add warning log to indicate that CTS will still continue

e2e/api_test.go
This temp directory name was conflicting with the get task test.
=> Update directory name to be unique

command/cli.go, command/commands.go, command/commands_test.go, command/start.go, command/start_test.go
When running CTS without a command, CLI space separate flag/value is not being interpreted correctly.
eg. `consul-terraform-sync -flag foo` `foo` is being interpreted as a command instead of as a value for `-flag`
When the the CLI library is invoke, it will attempt to find the command anywhere in the passed in args. That means that if no command is passed, it will interpret config.hcl as the command if `consul-terraform-sync -config-file config.hcl` is used to start the daemon.
We did not run into this issue previously as we used to only use the cli library if the first argument was not a flag (contained `-`). Now we use the CLI library for everything, and it will run the start command as the default command.
Pre-process the args and tack on the default command (start). Not ideal, but …
=> Fixed issue with flags when running CTS without start command

command/task_enable.go
`-auto-approve` flag is supported for `task enable`
https://www.consul.io/docs/nia/cli/task#usage-1
CLI output with this change:
```
$ ./consul-terraform-sync task enable task_a -
-auto-approve  -client-cert   -port
-ca-cert       -client-key    -ssl-verify
-ca-path       -http-addr
```
=> Add auto-approve flag to auto-completion for `task enable`

e2e/e2e_test.go
Ensures that both `=` and space-delimited argument values are parsed correctly for subcommands and the "default" command.
=> Add e2e test for argument parsing variants.

command/cli.go, command/cli_test.go, command/commands.go, command/commands_test.go, command/meta.go, command/start.go, command/task_create.go, command/task_delete.go, command/task_disable.go, command/task_enable.go, e2e/command_test.go, e2e/e2e_test.go
CTS does not behave as expected when attempting to get the version through the cli:
`consul-terraform-sync -version` 
outputs:
```linux
flag provided but not defined: -version
```
No variations of the version flag work correctly `-v`, `--version`, `--version`
This bug was introduced after fixing #870
To support pre-existing behavior in CTS where CTS can be run as a daemon without the `start` command, some preprocessing to arguments needed to be performed in order to make the CLI library believe a `start` command was used. This caused the CLI library to interpret `consul-terraform-sync -version` as `consul-terraform-sync start -version` which is invalid.
Parse passed in args for `-v`, `--version` and `-version` and do not pre-process the args if present. Let the CLI library handle …
=> version not outputted anymore after fix running CTS without a command

controller/daemon.go, e2e/registration_test.go, go.mod, go.sum
Registration moved before once mode runs
To accommodate this change, HCAT has been upgraded with a fix for #884 as placing the registration before once mode made this issue occur more frequently.
This PR resolves #884
=> move registration before once mode

config/config_test.go, config/consul_test.go, config/service_registration.go, config/service_registration_test.go, config/testdata/long.hcl, config/testdata/long.json, e2e/registration_test.go, registration/manager.go, registration/manager_test.go, testutils/consul.go
Adds a new `address` configuration to the `consul.service_registration` block. Note that this configuration is purposefully  different than the `address` under `default_check`.
```
consul {
service_registration {
address = "123.456.789"
}
}
```
=> Add configuration option for CTS service address

.circleci/config.yml, .gitignore, Makefile, build-scripts/split-tests.sh
- Introduced a test splitter that finds all tests in a package (e2e in our case) and creates N files each with a regex that only runs 1/N of the tests.
- Added parallelism to the e2e-tests step in CircleCI. 3 jobs run in parallel, each running a different set of tests.
- Switched from go test to gotestsum for running e2e tests, unit and integration tests
- Cleaner colorful output
- Test results xml generation
- Added a step to upload test-results to CircleCI
- Refactored circleci config
- Removed obsolete go modules cache
=> E2E test results and concurrency

.github/CODEOWNERS, CODEOWNERS
This locks down changes to release directories so that they require approval from release engineering, and so they have service account rights for pipeline runs and backport-assistant functionality.
=> Add codeowners file for releng dirs

go.mod, go.sum
Context: v1.5.3 has a CVE with a rebuttal under review. Regardless, it causes
the security scanner to fail. Going ahead and making this upgrade in case of
future patch releases.
Changelog Audit:
- 1.5.4: Bug fixes and improvements. Requires Go v1.15+
- 1.5.5: Improvement
- 1.5.6: Update around gpg signing
- 1.5.7: Update around gpg signing
- 1.5.8: Improvement
- 1.5.9: bug fix
- 1.5.10: Update around Google cloud storage. Fix regression from v1.5.9
- 1.5.11: Update test. Improvement to redact SSH key from URL query params
- 1.6.0: Improvement
- 1.6.1: Dependency update
=> Upgrade go-getter from v1.5.3 to v1.6.1

e2e/compatibility/consul_test.go
Per CTS compatibility [documentation](https://www.consul.io/docs/nia/compatibility#consul), Consul 1.8+ are supported. I removed older/no-longer-supported Consul versions from the compatibility tests.
=> Removed old Consul versions from compatibility tests

Makefile, driver/terraform_download.go, e2e/compatibility/terraform_download_test.go
The configuration provided to hc-install caused issues
whenever a version of terraform was located on the PATH
but not the application workdir. Since logic already
exists to check the workdir and version of the executable
prior to hc-install execution, the fs-check can be removed.
=> Remove incorrect path lookup for terraform install.

CHANGELOG.md, Dockerfile, docker/Dockerfile
Add missing ssh command to docker image so that TF can utilize the protocol to download packages.
https://github.com/hashicorp/consul-terraform-sync/issues/940
=> Add openssh to docker image.

e2e/command_test.go
This helper method currently uses the same task name for both enterprise and oss testing. Changing the task name to a parameter helps prevent concurrent test execution from failing unexpectedly.
=> Parameterize task name for enterprise.

controller/daemon_test.go, controller/driver_factory.go, controller/driver_factory_test.go, controller/inspect_test.go, controller/once_test.go, controller/tasks_manager_test.go
This change is necessary to better support TerraformCloud and
enterprise. There may be scenarios where we need to perform
I/O during initialization of a driver. Adding a context will
allow for proper cancellation.
=> Add context to driver factory.

.github/workflows/ci.yml, .github/workflows/weekly-tests.yml
Failing benchmark make command now correctly fails the GH action. See https://github.com/hashicorp/consul-terraform-sync/runs/6905394540?check_suite_focus=true
=> Added pipefail to GHA run commands

client/consul.go, client/consul_test.go, mocks/client/consul.go
Adds the following to the Consul client interface:
- Creating a session with retries
- Periodically renewing a session
- Creating a lock handler
- Locking a lock
- Unlocking a lock
- Getting a Consul KV pair
Periodic session renewal, creating a lock handler, locking, and unlocking are methods that the Consul API library provides for common use cases and not direct API requests. They're added in this interface for easier testing, but just call the underlying Consul API client method.
=> Support for sessions, locks, and KV get in Consul client

client/terraform_exec_test.go, go.mod, go.sum
Fixes: https://github.com/hashicorp/consul-terraform-sync/issues/849
Commits:
- Adds a test to show issue with leaked goroutines (test fails)
- Pulls latest tf-exec version (test passes)
=> Upgrade to terraform-exec v0.17

client/terraform_exec_test.go
Test_TerraformExec_Leak was a little flakey with GHA (see error below). Swap
from using the CTS wrapper around terraform-exec (which did other stuff like
change workspaces) and use terraform-exec directly to init and apply.
```
Error: -23T20:45:45.954Z [ERROR] client.terraformcli: unable to change workspace: workspace="" error="exit status 1"
terraform_exec_test.go:60:
Error Trace:	terraform_exec_test.go:60
Error:      	Not equal:
expected: 22
actual  : 24
Test:       	Test_TerraformExec_Leak
Messages:   	the number of goroutines after the terraform requests should be the same as before
```
Testing:
- Without this fix: 3/4 GHA runs failed ([Click through "Latest" drop down on left](https://github.com/hashicorp/consul-terraform-sync/actions/runs/2552170140))
- With this fix: 0/4 GHA runs …
=> Update Test_TerraformExec_Leak to use tf-exec directly

.release/security-scan.hcl
We have a failing CRT security scan that is being looked into by the release engineering team
https://github.com/hashicorp/crt-workflows-common/runs/7025669481?check_suite_focus=true
It's complaining about a secret, a vault token, contained within the binary. To my knowledge we haven't added anything, so was hoping to look at the binary to see if it contained any clues.
Highly suspect this is a false positive, suggestion was to provide a list of secret scanning only for the secret types we're interested in.
[List of secret matchers](https://github.com/hashicorp/security-scanner/blob/f9ef022e3ba7801f867ded9ef4a717c1d06a7ebe/pkg/scanner/secrets.go#L90-L125)
=> added list of known secret matchers

controller/once.go, controller/once_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go
We want to be able to support when once-mode does not exit on error. One use-case for this is when the tasks have been known to run successfully before. When CTS starts up, we expect the tasks to be successful and any errors are intermittent. In this case, we want CTS to not exit and just log the error.
Commits
- 1 & 2: Split out error test case for `Test_Once_Run_Terraform` in preparation for new error case in commit 4
- 3: Add TaskFailsSilently (open to better naming ideas) in tasks manager
- 4: Update once-mode with a failSilently flag that calls TaskFailsSilently when true
Edit: from PR feedback changed "fail silently" language to "allow fail"
=> Support once-mode failing silently

.github/workflows/ci.yml, e2e/command_test.go
This change ensures that when a single part of e2e tests fails, the other parts continue executing and are not skipped.
Tested with an intentional failure:
=> Run Full E2E Matrix (CI)

command/cli.go, command/start.go
Help output was missing a new line at the end, resulting in this output
```
bash-3.2$ consul-terraform-sync -h
Usage CLI: consul-terraform-sync <command> [-help] [options]
...
Render templates and run tasks once. Does not run the process 
as a daemon and disables buffer periods.bash-3.2$ 
```
After adding the new line at the end, this is the output
```
bash-3.2$ consul-terraform-sync -h
Usage CLI: consul-terraform-sync <command> [-help] [options]
...
Render templates and run tasks once. Does not run the process 
as a daemon and disables buffer periods.
bash-3.2$ 
```
=> Added missing new line at the end of help output

config/config_test.go, config/task.go, config/task_test.go, controller/daemon.go, controller/once.go, e2e/e2e_test.go
This PR serves to remove the requirement that CTS be run with initial configuration tasks.
When CTS is run without initial configuration tasks, it will forgo running once mode and monitor for new tasks/serve the API. If a new task is created via the API/CLI, then CTS will monitor and trigger as before.
If CTS is run with initial configuration tasks, runs as usual.
=> Allow cts run without initial task

client/consul.go, mocks/client/consul.go
Mocks generated with the expecter flag will have code that makes
it easier to setup the behavior of the mocked methods.
=> Generate Consul client mocks with expecter

api/test.go
Wasn't returning the pointer, so the command output wasn't being logged on a
test failure.
=> Fix command buffer to return properly

e2e/condition_schedule_test.go
- tasks with schedule condition can create 1 or more events depending on how close to the trigger time creation occurs due to when the test runs
=> loosen schedule condition checks

config/decode.go
```
2022-07-28T16:51:48.116-0500 [ERROR] cli: error building configuration:
error=
| 'config.hcl' has invalid keys: high_availability
| 
| High availability is a Consul-Terraform-Sync (CTS) Enterprise feature.
| Upgrade to Consul Enterprise to enable CTS Enterprise features.
```
=> Error if HA config provided

controller/tasks_manager.go
The old channel size would not allow for more than 10 scheduled
tasks to be defined on startup. Once-mode would hang, because the
scheduled channel consumer was not yet initialized. This tweak
allows for up to 100 scheduled tasks to be defined before blocking.
=> Allow for 100 scheduled tasks during once-mode.

CHANGELOG.md, controller/tasks_manager.go
- Add HA to changelog
- Update error message in TaskCreateAndRunAllowFail for new troubleshooting steps
Sample log message:
```
2022-08-02T16:59:29.614-0400 [ERROR] tasksmanager: error creating driver for task.
Please investigate this error. This may require manual intervention to fix and
then restarting the instance for changes to take effect: task_name=lorna_task
error=
| error tf-init for 'lorna_task': exit status 1
| 
| Error: Module not found
| ...
```
=> Update changelog & log message

Dockerfile
Changes proposed in this PR:
In `actions-docker-build` we [pass](https://github.com/hashicorp/actions-docker-build/blob/05c370a26e61b06be46c5095d6e914c9f0ea4f3d/scripts/docker_build#L49) `PRODUCT_VERSION` to the docker build command. Since this was not set, the label did not populate properly which is used in a comparison to determine the `minor-latest` and `latest` docker image tags. 
```
docker inspect hashicorp/consul-terraform-sync:latest -f={{json '.Config.Labels'}} | jq
{
"maintainer": "Consul Team <consul@hashicorp.com>",
"version": ""
}
```
=> set PRODUCT_VERSION for default docker build

templates/tftmpl/tmplfunc/services_regex.go
Issue - NET-4886
Issue - 
When services are registered with checks, initially they are in `critical` status. When health check passes, they get in `passing` status.  Without this delay, CatalogServices may have services that are not yet propagated to HealthServices as healthy services since services are initially set as critical. 
The API call from CTS to Consul has `passing` [set to true](https://github.com/hashicorp/consul-terraform-sync/blob/main/templates/tftmpl/tmplfunc/services_regex.go#L209). It only returns passing health check services or healthy services.
The delay is small. It might take more time to make service healthy. Hence this PR increases the delay.
Tests - 
Manually tested it using Nomad and Consul + CTS setup using Terraform Cloud driver. Changes in PR has resolved the …
=> Increase time.Sleep

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/weekly-tests.yml, CHANGELOG.md, config/monitor_services.go, config/task.go, e2e/condition_schedule_test.go, e2e/condition_service_test.go, e2e/module_input_test.go, e2e/utils.go, examples/reference-example/sync-tasks/my-task/main.tf, go.mod, internal/decode/decode.go, mocks/api/middleware.go, mocks/client/consul.go, mocks/templates/template.go, mocks/templates/watcher.go, templates/hcltmpl/block.go, templates/tftmpl/root.go, templates/tftmpl/root_test.go, templates/tftmpl/testdata/catalog-services/main.tf, templates/tftmpl/testdata/main.tf, templates/tftmpl/tmplfunc/catalog_services_registration.go, templates/tftmpl/tmplfunc/services_meta.go, templates/tftmpl/tmplfunc/services_regex.go, testutils/utils.go, version/terraform.go, version/terraform_test.go
Bump Go Version - 1.20.10
Updated Terraform Version - 1.6.2
Make E2E tests passing
=> NET 6318 - Go/Terraform Version Upgrade + E2E passing

.release/security-scan.hcl
Suppressing following CVEs as it is causing breaking changes and we need to fix CVE CVE-2024-6387 for JPMC customer
"GHSA-v6v8-xj6m-xwqh", # github.com/hashicorp/go-retryablehttp@v0.7.0
"GO-2024-2947", # github.com/hashicorp/go-retryablehttp@v0.7.0
"GO-2025-3533" # github.com/getkin/kin-openapi@v0.94.0
=> Suppressing CVEs
