hashicorp/consul-terraform-sync

client/terraform_cli.go, client/terraform_cli_test.go
Executing terraform init for a non-default workspace that has an empty state causes an error. This adds edge case handling of the Terraform error to init, check the error, create workspace (which also sets up the backend), and init again.
This error is commonly ran into when using the default CTS option for Terraform state store, Consul KV. During development, the Consul server may be restarted and wiping the in-memory Consul KV along with the Terraform state files for CTS tasks. This also happens for other backends, in addition to Consul KV, when an existing task's state has been deleted because `.terraform/environment` manifest file with the workspace name is written to disk and subsequent inits have context of that workspace but not its state.
I chose to leave the …
=> Fix err for non-default workspace with empty state

config/config.go, config/config_test.go, config/vault.go, config/vault_test.go, go.mod
PR to add configuration option for connecting with Vault. The vault configuration is not used by the project at the moment and is setting up for upcoming PRs to support loading configuration for Terraform providers from various sources.
Related #53
=> Add vault config option

handler/panos.go, handler/panos_test.go
The default behavior for panos using API key commits all changes queued up by any user. This poses a security risk of auto-committing unverified changes by other users. Setting admin changes the behavior to a partial commit and only commits the changes made by the user.
**Caveat**
Panos does not have an API to fetch the associated username fro the API key. It is up to the practitioner to configure the correct username for the key. If the username does not match the key, it will attempt to auto-commit for that user, which may or may not exist or have changes, and will not commit changes made by Consul-Terraform-Sync.
Cases tested:
=> Support panos partial commit to admin user

api/api_test.go
This is likely caused by the test making http requests before the api server is
ready. I was able to reproduce this error message locally by adding a sleep in
Serve(). Logs show no additional error messages i.e. the server looks like it
started successfully and had not stopped
Change: on receiving a connection refused error message, wait and retry once
=> Flakey api Serve() test returning connection refused

e2e/api_test.go
There is a race condition when waiting after a service is registered to collect
a number of events per task. Previously we were expecting a specific number of
events. However, waiting too short/long led to too few/many events collected per
task, which can cause the test to fail. This change is pre-emptively adding some
flexibility to this test by allowing a range of expected events.
=> Allow a range of events in status e2e test

config/config.go, config/config_test.go
`provider` block name was deprecated in [v0.1.0-techpreview2](https://github.com/hashicorp/consul-terraform-sync/blob/master/CHANGELOG.md#010-techpreview2-december-16-2020), it is removed in v0.1.0-beta.
related PR https://github.com/hashicorp/consul-terraform-sync/pull/140
=> Remove deprecated provider block with special error handling

handler/panos.go, handler/panos_test.go, retry/retry.go
Recommendation at this point was to retry only once after a decent delay
based on SE feedback.
Retry is very simple and groups together the commit and wait calls as
either could fail (both make http calls to the panos API with failure
conditions).
Added checks to existing tests as they already provided decent coverage.
--
PR notes:
1) what do you think of the the retry tests using expectedRetries() vs. including the expected retries in the table data?
=> simple, single retry for panos' commit

templates/tftmpl/integration_test.go
`TestRenderTFVarsTmpl/happy_path` occasionally fails where the templated service
information is missing one or two of the registered services. Of the 4 fails
observed, two are missing api.worker-01.dc1 and api-2.worker-01.dc1. The other
two are missing web.worker-01.dc1
I haven’t been able to debug this successfully (it started passing when I tried).
This change is a pre-emptive measure to increase the context cancel a little and
retry the test once in case the race is between the test and the services
registering.
=> Attempt to improve consul service templating flakiness

config/config_test.go, config/task.go, config/task_test.go
Will be consumed by task driver and status in subsequent pr to support enable / disable CLI
=> Add `enabled` field to task configuration

api/client.go, api/client_test.go, driver/driver.go, driver/terraform.go, mocks/driver/driver.go
Changes (each correspond with a commit. See individual commit messages for
more details):
- Add driver.Task() so that we can view state of task for testing (and Status
API down the line)
- Add API client
=> Add API client for Update Task API

api/api.go, api/task.go
```
2021/02/22 20:37:23.267091 [INFO] (api.task) Updating task 'a' to be enabled=true
```
=> Add task name to update API logs

go.mod, go.sum
=> update hashicat to latest version

api/client.go, api/task_test.go, client/printer_test.go, driver/terraform_test.go
Commits
- Removed some unreachable code found while looking at coverage
- Add a few missing tests
=> Add tests for some missing coverage from enable/disable cli development

e2e/benchmarks/services_test.go, e2e/test_modules/null_resource/main.tf, e2e/test_modules/null_resource/variables.tf
I already have a case and I know @lornasong thought this would be useful.
=> split out null_resource test module for reuse

e2e/benchmarks/services_test.go, testutils/consul.go
Move the functions used to load consul with test servers/instances into
the testutils module for reuse in other tests.
Also moved the ShowMe* functions as they are also generally handy.
Cleaned up the loading functions a bit and refactored the existing tests
to use the shared functions instead of the old, local versions.
=> move bulk consul service loading to testutils

e2e/benchmarks/services_test.go, e2e/render_test.go, testutils/consul.go
Note this is branched off the bulk-loader-util branch and depends on it being merged first.
Fixes #236
=> Services render race test

api/api_test.go
The retry was no longer working because testutils.RequestHTTP no longer returns
an error and instead checks & handles errors within. The err that was attempted
to be handled for the retry was actually an err from above FreePort().
Change: wait a little after serving the API before testing endpoints. 3s is
used in other places in our code for serving the API and it so has so far
worked well for those tests e.g. api/client_test.go
=> Fix api-serve unit test race condition retry

go.mod, go.sum
=> update hcat version for render-complete race fix

api/task.go, api/task_test.go
When a task is disabled and then enabled via CLI, the task may execute if there
are changes. Whenever a task executes, an event should be stored.
When enable CLI was implemented, storing an event on task execution was
unintentionally not implemented. This change fixes this and stores an event.
Changes:
- Identifies when a task is executed: when ?run=now i.e. runOp == driver.RunOptionNow
- Stores an event
- Retrieves an error that may result from driver.UpdateTask to store in the event
Fixes: https://github.com/hashicorp/consul-terraform-sync/issues/318
=> Store an event when a task becomes enabled and executes

CONTRIBUTING.md, README.md
Detailed guidelines on contributing to CTS and Public roadmap with categories and FAQs
=> added public roadmap details to README and contribution guidelines

api/api_test.go, api/server_test.go, api/test.go, e2e/compatibility/consul_test.go, e2e/render_test.go, handler/panos_test.go, templates/hcltmpl/integration_test.go, testutils/utils.go, testutils/utils_test.go, testutils/vault.go
Various test improvements I came across
Changes:
- Stop watcher in TestServicesRenderRace
- Add testutils.Setenv()
- Tidy up testutils.FreePort()
=> Updates to testutils

.github/workflows/build.yml
=> fix upload

.github/workflows/build.yml, packaging/docker/Makefile
As per - https://github.com/hashicorp/crt-core-helloworld/pull/7
=> Moving docker build to it's own job 

controller/readwrite.go, controller/readwrite_test.go, driver/task.go, driver/terraform.go, e2e/condition_schedule_test.go, e2e/condition_test.go, templates/tftmpl/notifier/suppress_notification.go, templates/tftmpl/notifier/suppress_notification_test.go
Supports running schedule condition for a task monitoring `task.services`. Subsequent changes
will support monitoring services via regex configuration and monitoring Consul KV. Schedule
condition config added previously https://github.com/hashicorp/consul-terraform-sync/pull/378
Changes
- Adds a custom notifier to suppress notification to watcher for scheduled task dependencies
- Adds e2e testing scheduled tasks
- Updates controller to handle running and triggering scheduled tasks separately from
dynamic tasks
**Usage:**
Sample configuration to test out scheduled conditions:
```
log_level = "DEBUG"
consul {
address = "localhost:8500"
}
task {
name = "periodic10_task"
description = "runs every 10 seconds and creates a txt for each instance of web and db"
services = ["web", "db"]
source = …
```
=> Support running scheduled tasks

driver/task.go
Shoutout to @wilkermichael for finding this bug!
=> Fix issue with Consul KV and namespaces

.release/docker/Dockerfile
This package is needed in the docker entrypoint.
=> add dumb-init package to dockerfile

api/api.go
Added to address TLS handshake errors when the client is misconfigured,
but will handle any errors the server code logs.
Example of previous error format:
```
2021/11/09 12:30:44 http: TLS handshake error from [::1]:54789: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "localhost")
```
Updated version:
```
2021-11-12T13:39:06.898-0600 [WARN]  api: http: TLS handshake error from [::1]:62111: tls: failed to verify client certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "localhost")
```
~~I have it set to infer the log level, …
=> Use standard logger for any server errors

CHANGELOG.md
Adds https://github.com/hashicorp/consul-terraform-sync/issues/516 to 0.4.2 changelog
=> Add known issue to changelog #516

e2e/compatibility/consul_test.go
Passing Consul Compatibility: https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/2527/workflows/af50a61b-f781-4b2b-b190-e418cec2bca5/jobs/5609
=> Wait for event before checking files

.github/workflows/build.yml
This updates the ECR tag to the correct naming convention. 
Signed-off-by: Scott Macfarlane <smacfarlane@hashicorp.com>
=> Update ECR tag in CRT Builds

api/oapigen/client.go
There was an error with the committed generated code, fixing that
=> re-generated client code

docker/Dockerfile
backport of commit 2f8c8d755113711bd20b7cf2f26b6eb72ee51eab
=> Backport of Remove arm v5v6 build references into release/0.2.x 

.github/workflows/build.yml
Please merge after approval, thank you.
=> update actions-generate-metadata to v1

e2e/command_test.go
Create Task tests were checking events for the task created when CTS starts up, not the task created via the CLI.
Tests have been updated to now check for events using the correct task name
=> Fixed create task command test cases

.github/workflows/build.yml, .release/ci.hcl, .release/docker/docker-entrypoint.sh, .release/security-scan.hcl, Dockerfile, Makefile, build-scripts/version.sh, version/version.go
This PR enables CRT for the `release/0.3.x` branch. 
Tests are passing [here.](https://github.com/hashicorp/crt-workflows-common/actions/runs/1775487996)
=> [RDX-272] Enable CRT for release/0.3.x branch

api/api.go, api/api_test.go, api/client.go, api/representation_test.go, api/response_writers.go, api/server_test.go, api/task.go, api/task_create_test.go, api/task_lifecycle_client.go, api/task_status.go, api/task_status_test.go, api/test.go, command/cli.go, docker/Dockerfile, e2e/api_test.go, e2e/command_test.go, e2e/command_tls_test.go, e2e/compatibility/consul_test.go, e2e/condition_consul_kv_test.go, e2e/e2e_test.go, e2e/tasks_test.go, e2e/utils.go
Improved tests - added missing asserts, removed overriding builtin 'delete', unified naming
Removed redundant type declarations and casting
Removed conflicts with package names
Improved naming and comments
Unified usage of 'require' test package instead of a mix of require and assert
=> Cleanup and Test Improvements

api/client.go, api/client_test.go
Improved tests/cleanup for API client
Added unit tests for API client
Improved environment lookup for API client creation
Unified using of 'require' test package instead of a mix of 'require' and 'assert'
=> API Client Improvements and Tests

api/client.go, api/client_test.go, api/server_test.go, api/task_lifecycle_client.go, api/test.go, command/cli.go, command/meta.go
Added and improved unit tests for client config and different clients
Refactored client config and client to use URL instead of a mix of schema/addr/port
Moved logic for handling port flag outside of client
Added validation for address
=> Client Refactoring and Testing

controller/readwrite.go, controller/server_test.go, driver/driver.go, driver/terraform.go, mocks/driver/driver.go, templates/tftmpl/notifier/catalog_services_registration.go, templates/tftmpl/notifier/consul_kv.go, templates/tftmpl/notifier/notifier.go, templates/tftmpl/notifier/notifier_test.go, templates/tftmpl/notifier/services.go, templates/tftmpl/notifier/suppress_notification.go
Addresses https://github.com/hashicorp/consul-terraform-sync/issues/704
e2e tests coming
=> Hanging trigger issue

api/task_lifecycle_client.go, e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/config.go
First round of tests for https://github.com/hashicorp/consul-terraform-sync/issues/704,  which pass now and [failed](https://app.circleci.com/pipelines/github/hashicorp/consul-terraform-sync/3389/workflows/7ea1a920-e929-46de-888d-9626ad2652bb/jobs/9134) before the bug fixes were merged to `main`.
=> [Part 1] E2E tests for creating a task with a shared dependency

e2e/condition_catalog_service_test.go, e2e/condition_consul_kv_test.go, e2e/condition_schedule_test.go, e2e/condition_service_test.go
Continuation of https://github.com/hashicorp/consul-terraform-sync/pull/707. Tests for https://github.com/hashicorp/consul-terraform-sync/issues/704.
=> [Part 2] E2E tests for creating a task with a shared dependency

.release/security-scan.hcl
Related slack thread: https://hashicorp.slack.com/archives/C010VJT0FRP/p1646936500488179
This PR will need to be backported to all active release branches, and to the active enterprise release branches. Feel free to apply the appropriate labels & merge when ready. Thanks!
=> Temporarily turn off NVD sec scanning

client/consul.go, client/consul_test.go, testutils/utils.go
Added round-tripper test setup
Removed testing for private method and added testing for public methods
=> Improved testing of Consul client

README.md
- Updated verify section in readme
- Fixed typos in readme
=> Updated verify section in readme

Makefile, go.mod, go.sum
- Adds race detector to e2e tests
- Addresses a race condition ([details](https://github.com/hashicorp/hcat/pull/100))
=> Add race detector to e2e tests

client/consul.go, client/consul_test.go, retry/retry_test.go
Added unit tests for the new error types, want to be consistent and test all public methods exported by packages
=> added tests for the error types

api/api_test.go, api/overall_status.go, api/overall_status_test.go, api/representation.go, api/server.go, api/server_test.go, api/task_get.go, api/task_get_test.go, api/task_status.go, api/task_status_test.go, controller/condition_monitor.go, controller/condition_monitor_test.go, controller/daemon.go, controller/daemon_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go, e2e/benchmarks/tasks_concurrent_test.go, mocks/server/server.go
Context: previously merged in a number of prs refactoring TasksManager and ConditionMonitor out of controllers.
Changes: various cleanup from feedback and minor issues noticed during refactoring
=> TasksManager & ConditionMonitor refactor cleanup

e2e/api_test.go, testutils/utils.go
Added E2E Tests
- health endpoint http/https tests
- get all tasks endpoint http tests (https will have automated tests when get is added to CLI)
=> added e2e tests

config/auth.go, config/buffer_period.go, config/buffer_period_test.go, config/condition_no.go, config/config_test.go, config/provider.go, config/tls.go, config/tls_cts.go, config/vault.go, controller/condition_monitor.go, controller/daemon.go, controller/driver_factory.go, controller/inspect_test.go, controller/tasks_manager.go, driver/task_test.go, driver/terraform.go, driver/terraform_test.go, e2e/compatibility/consul_test.go, e2e/registration_test.go, templates/tftmpl/template_catalog_services.go, testutils/consul.go, testutils/sdk/sdk.go
Fixing lint warnings, simplifying parts of the code.
=> Fixed linting warnings

README.md
Added one line for the survey link, added a "overview" title for the first section.
=> Added survey link to the CTS readme file. 

.release/security-scan.hcl
=> fixed formatting

api/test.go
Some test scenarios require more control on how CTS is started and stopped,
so moved the the command creation and the steps to generate a port and write
it to the config file into a separate method.
=> Method for constructing command and setting port

config/buffer_period.go, config/buffer_period_test.go, config/config.go, config/config_test.go, config/task.go, config/task_test.go, controller/condition_monitor_test.go, controller/driver_factory.go, controller/once_test.go, controller/tasks_manager.go, controller/tasks_manager_test.go, state/in_memory_store_test.go
=> Fix issue with task config incorrectly modified

controller/tasks_manager.go
Noticed there were some missing public comments on Task Manager, so added those in
=> Updated task manager public comments

Makefile
=> Force parallel e2e test execution.

api/api.go, api/api_test.go, api/handler.go, api/oapigen/client.go, api/oapigen/server.go, api/oapigen/types.go, api/openapi.yaml, api/status.go, api/status_test.go, client/consul.go, client/consul_test.go, mocks/api/oapigen_client.go, mocks/client/consul.go, retry/retry.go
This PR contains reviewed changes from Enterprise that are being ported to OSS
=> backport ent changes

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/weekly-tests.yml, CHANGELOG.md
=> bump go version to 1.22.4

CHANGELOG.md, version/version.go
=> prepping for 0.7.2 release

.release/ci.hcl, .release/security-scan.hcl, CHANGELOG.md, version/version.go
=> prepping for 0.7.3 release
